import { ArrowRight, Check, ChevronDown } from "lucide-react";
import { useState } from "react";

import { NavigationButton } from "@/components/navigation";
import { IndustrySectorsSection } from "@/components/sections/IndustrySectorsSection";
import { RouteMeta } from "@/components/seo/RouteMeta";

const shell = "mx-auto w-[calc(100%-2.5rem)] max-w-[1240px] max-[600px]:w-[calc(100%-1.75rem)]";
const section = "py-24 max-[600px]:py-16";
const heading = "font-['Source_Serif_4',Georgia,serif] text-[clamp(42px,5vw,68px)] leading-[1.02] tracking-[-.04em]";
const eyebrow = "mb-4 flex items-center text-[10px] font-bold uppercase tracking-[.17em] text-kbc-purple-600";

const publicValue = [
  ["01", "Formal baselines and controlled change", "Material changes to scope, cost or timetable require clear impact analysis, approval routes and traceable decisions."],
  ["02", "Accountability and value for money", "Reporting must support governance, assurance and the responsible use of public funds rather than simply describing activity."],
  ["03", "Multi-supplier delivery ecosystems", "Dependencies, commercial interfaces and shared milestones must be coordinated across departments, partners and suppliers."],
  ["04", "Data, security and service continuity", "Planning and controls must respect information governance, access requirements, resilience and critical-service responsibilities."],
];
const capabilities = [
  ["01", "Planning and scheduling", "Roadmaps, baselines, milestones, dependencies, progress and scenario planning."],
  ["02", "Cost and forecasting", "Budgets, commitments, estimates, variance, affordability and forecast confidence."],
  ["03", "Risk and change", "Risk appetite, escalation, impact assessment, change control and mitigation."],
  ["04", "Performance reporting", "Integrated data, RAG status, trends, dashboards and decision-ready narrative."],
  ["05", "Governance and assurance", "Evidence, auditability, approvals, public accountability and value for money."],
];
const routes = [
  ["01", "Associate Project Manager", "For employees coordinating projects, managing workstreams, supporting governance and developing professional project-management capability."],
  ["02", "Project Controls Professional", "For planners, cost professionals, risk specialists, controls engineers and PMO teams responsible for integrated delivery performance."],
  ["03", "Project Delivery Functional Standard", "Consistent expectations for governance, assurance, roles and delivery practice."],
  ["04", "Green Book and Five Case Model", "Appraisal, business cases, options, benefits and demonstrable public value."],
  ["05", "Orange Book", "Risk management embedded in governance, decisions and organisational objectives."],
  ["06", "Managing Public Money", "Probity, regularity, affordability, financial discipline and responsible decision-making."],
];
const progression = [
  ["01", "Project support", "Project Support Officer, Project Coordinator or Junior PMO Analyst."],
  ["02", "Project delivery", "Project Manager, Workstream Lead or developing delivery professional."],
  ["03", "Specialist controls", "Planner, Scheduler, Cost Engineer, Risk Professional or Controls Engineer."],
  ["04", "Controls leadership", "Project Controls Lead, Programme Controller or PMO Controls Manager."],
  ["05", "Programme leadership", "Programme Controls Manager, Head of PMO or senior project-delivery leader."],
];
const journey = [
  ["01", "Capability review", "Discuss roles, organisational priorities and target capability."],
  ["02", "Eligibility and prior learning", "Review the employee, workplace, existing knowledge and funding route."],
  ["03", "Enrolment and learning plan", "Agree responsibilities, support, development goals and evidence opportunities."],
  ["04", "Applied development", "Live sessions, coaching, workplace application, progress reviews, Gateway and EPA preparation."],
];
const faqs = [
  ["Can an existing public-sector employee complete an apprenticeship?", "Yes. Apprenticeships can develop eligible existing employees while they remain in a productive role, subject to suitability and current funding rules."],
  ["Which route is right for project support or coordination roles?", "Associate Project Manager Level 4 may suit employees coordinating delivery, workstreams, stakeholders and governance information."],
  ["Who is the Project Controls Professional Level 6 route designed for?", "It is designed for planners, cost professionals, risk specialists, controls engineers and PMO teams responsible for integrated delivery performance."],
  ["Are the apprenticeships fully funded?", "Funding is not automatic. It depends on the employer, learner, programme, prior learning, available allocation and current apprenticeship rules."],
  ["What does the employer need to provide?", "The employer supports agreed learning activity, workplace application, relevant evidence opportunities, progress reviews and learner development."],
  ["How is workplace impact reviewed?", "Impact is discussed through progress reviews and demonstrated through authentic workplace outputs, evidence and reflection."],
];

export default function SectorsPage() {
  const [openFaq, setOpenFaq] = useState<string | null>(null);
  return <div className="bg-white font-['DM_Sans',sans-serif] text-kbc-purple-950 [&_h1]:font-['Source_Serif_4',Georgia,serif] [&_h2]:font-['Source_Serif_4',Georgia,serif] [&_h3]:font-['Source_Serif_4',Georgia,serif]">
    <RouteMeta fallbackTitle="Public-Sector Project Apprenticeships | Kent Business College" fallbackDescription="Funded Level 4 and Level 6 apprenticeships for public-sector project support, project management, controls and PMO teams." />

    <section className="overflow-hidden bg-gradient-to-br from-kbc-purple-950 via-kbc-purple-900 to-kbc-purple-800 text-white">
      <div className={`${shell} grid min-h-[650px] grid-cols-[0.95fr_1.05fr] items-center gap-20 py-16 max-[900px]:grid-cols-1 max-[900px]:gap-10 max-[900px]:py-14`}>
        <div><p className="inline-flex items-center gap-2 rounded-full border border-kbc-gold-500/40 px-4 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-kbc-gold-500 before:h-2 before:w-2 before:rounded-full before:bg-kbc-gold-500">Public-sector project apprenticeships</p><h1 className="kbc-hero-title mt-7 max-w-[610px]">Build public-sector project delivery capability that <span className="text-kbc-gold-500">stands up to scrutiny.</span></h1><p className="mt-7 max-w-[600px] text-[15px] leading-7 text-white/75">Funded Level 4 and Level 6 apprenticeships for project support professionals, project managers, planners, project controls specialists and PMO teams working across government and public services.</p><div className="mt-6 flex max-w-[600px] flex-wrap gap-2">{["Existing employee development", "Project management and controls", "Live online delivery", "Workplace evidence"].map((item) => <span className="rounded-full border border-white/20 px-3 py-2 text-[11px] text-white/75" key={item}>{item}</span>)}</div><div className="mt-7 flex max-w-[620px] flex-wrap gap-3"><NavigationButton className="!min-h-12" to="/book-session" variant="projectControls">Book an employer capability review</NavigationButton><NavigationButton className="!min-h-12" to="#routes" variant="projectControlsInverse">Compare apprenticeship routes</NavigationButton><NavigationButton className="!min-h-12" to="#career-guide" variant="projectControlsInverse">Explore the career guide</NavigationButton></div></div>
        <div className="self-center overflow-hidden rounded-2xl border border-white/20 bg-white/5 p-3 shadow-2xl"><div className="relative"><img className="h-[330px] w-full rounded-xl object-cover object-center" src="/assets/images/sectors/public-sector-employer-journey.jpg" alt="Public-sector leaders in a programme governance meeting" /><span className="absolute left-5 top-5 rounded-full bg-kbc-purple-950/90 px-4 py-2 text-[10px] font-semibold text-white">Existing employee development</span><div className="absolute inset-x-0 bottom-0 rounded-b-xl bg-gradient-to-t from-kbc-purple-950 p-5 pt-16"><b className="text-sm text-white">Decision-ready information for accountable delivery.</b><p className="mt-1 text-[10px] text-white/65">Scope, schedule, cost, risk, change, assurance and public value.</p></div></div></div>
      </div>
      <div className="border-t border-white/15"><div className={`${shell} grid grid-cols-4 max-[800px]:grid-cols-2 max-[500px]:grid-cols-1`}>{[["Develop existing staff", "Eligible employees learn while remaining in role."], ["Use apprenticeship funding", "Levy, transfer or co-investment routes may apply."], ["Apply learning at work", "Projects and evidence connect to live responsibilities."], ["Prepare for assessment", "Progress reviews, Gateway and EPA preparation."]].map(([title, text]) => <div className="border-r border-white/15 p-6 last:border-r-0" key={title}><b className="text-sm text-white">{title}</b><p className="mt-2 text-xs text-white/60">{text}</p></div>)}</div></div>
    </section>

    <IndustrySectorsSection id="sector-focus" />

    <section className={section}><div className={shell}><div className="max-w-[830px]"><p className={eyebrow}>Why public-sector delivery is different</p><h2 className={heading}>Project capability must remain clear, auditable and defensible.</h2><p className="mt-5 max-w-[720px] text-kbc-purple-700">Public programmes operate across formal governance, multi-supplier delivery, constrained budgets, complex stakeholders and high levels of scrutiny. General project theory is not enough.</p></div><div className="mt-12 grid grid-cols-[1.05fr_.95fr] gap-5 max-[850px]:grid-cols-1"><article className="flex min-h-[430px] flex-col justify-end rounded-2xl bg-kbc-purple-950 p-8 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-kbc-gold-500">Public value</p><h3 className="mt-4 max-w-[420px] text-[clamp(36px,4vw,54px)] leading-[1.02] text-white">Public value changes the standard of evidence.</h3><p className="mt-5 text-sm text-white/70">Decisions must connect approved scope, affordability, risk, service outcomes and governance requirements. Teams need reliable controls that allow senior leaders to intervene early.</p><b className="mt-8 border-t border-white/15 pt-6 text-sm text-kbc-gold-500">Leaders need concise, decision-ready insight across schedule, cost, risk, change, benefits and delivery confidence.</b></article><div className="grid grid-cols-2 gap-4 max-[520px]:grid-cols-1">{publicValue.map(([number, title, text]) => <article className="rounded-2xl border border-kbc-purple-100 p-6" key={number}><span className="rounded-lg bg-kbc-purple-50 px-2 py-1 text-xs font-bold text-kbc-purple-600">{number}</span><h3 className="mt-6 text-xl">{title}</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">{text}</p></article>)}</div></div></div></section>

    <section className={`${section} bg-kbc-gold-50`}><div className={shell}><div className="max-w-[820px]"><p className={eyebrow}>Role-to-programme pathway</p><h2 className={heading}>Match the apprenticeship to the employee’s real responsibilities.</h2><p className="mt-5 text-kbc-purple-700">The right route depends on the role, prior learning, level of responsibility and the new capability the employee needs to develop.</p></div><div className="mt-12 grid grid-cols-[0.85fr_1.15fr] gap-5 max-[800px]:grid-cols-1"><article className="flex flex-col rounded-2xl bg-white p-8"><h3 className="text-4xl">Project support</h3><p className="mt-4 text-sm text-kbc-purple-700">For employees coordinating actions, documents, reporting, stakeholders and workstream activity.</p><a className="mt-auto pt-12 text-sm font-bold text-kbc-purple-600" href="#routes">Discuss an apprenticeship pathway <ArrowRight className="inline" size={16} /></a></article><div className="grid grid-cols-2 gap-3 rounded-2xl bg-white p-3 max-[520px]:grid-cols-1">{[["Project Support Officer", "Coordinates actions, documents, reporting and delivery support."], ["Project Coordinator", "Supports plans, stakeholders, risks and workstream activity."], ["Junior PMO Analyst", "Maintains governance information, reporting and standards."], ["Associate Project Manager Level 4", "Builds structured project-delivery capability."]].map(([title, text]) => <article className="rounded-xl bg-kbc-purple-50 p-5" key={title}><b className="text-sm">{title}</b><p className="mt-2 text-xs text-kbc-purple-700">{text}</p></article>)}</div></div></div></section>

    <section className={section}><div className={shell}><div className="mx-auto max-w-[850px] text-center"><p className={`${eyebrow} justify-center before:hidden`}>The project-controls capability model</p><h2 className={heading}>Build the five capabilities required for accountable public-project delivery.</h2><p className="mt-5 text-kbc-purple-700">A clear employer capability framework grounded in the realities of public-sector project delivery.</p></div><div className="mt-14 grid grid-cols-5 gap-4 max-[1000px]:grid-cols-2 max-[520px]:grid-cols-1">{capabilities.map(([number, title, text], index) => <article className={`rounded-2xl border p-6 ${index === 0 ? "border-kbc-purple-950 bg-kbc-purple-950 text-white" : "border-kbc-purple-100 bg-white"}`} key={number}><div className="flex items-center justify-between"><span className={index === 0 ? "text-kbc-gold-500" : "text-kbc-purple-600"}>{number}</span><b className={`rounded-lg px-2 py-1 text-xs ${index === 0 ? "bg-white/10 text-white" : "bg-kbc-purple-50 text-kbc-purple-600"}`}>{number}</b></div><h3 className={`mt-10 text-xl ${index === 0 ? "text-white" : ""}`}>{title}</h3><p className={`mt-3 text-xs leading-5 ${index === 0 ? "text-white/65" : "text-kbc-purple-700"}`}>{text}</p></article>)}</div></div></section>

    <section className={`${section} bg-kbc-purple-50`} id="routes"><div className={shell}><div className="max-w-[850px]"><p className={eyebrow}>Funded apprenticeship routes</p><h2 className={heading}>Two routes. One accountable project-delivery pathway.</h2><p className="mt-5 text-kbc-purple-700">Kent Business College reviews each employee’s role and prior learning before confirming the appropriate programme and funding position.</p></div><div className="mt-12 grid grid-cols-3 gap-4 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1">{routes.map(([number, title, text]) => <article className="rounded-2xl border border-kbc-purple-100 bg-white p-6" key={number}><span className="rounded-lg bg-kbc-purple-50 px-2 py-1 text-xs font-bold text-kbc-purple-600">{number}</span><h3 className="mt-6 text-xl">{title}</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">{text}</p></article>)}</div></div></section>

    <section className={section}><div className={shell}><div className="mx-auto max-w-[850px] text-center"><p className={`${eyebrow} justify-center before:hidden`}>Career progression</p><h2 className={heading}>Build a visible project-delivery capability pipeline.</h2><p className="mt-5 text-kbc-purple-700">Progress from project support through specialist controls and senior programme leadership.</p></div><div className="mt-12 grid grid-cols-3 gap-4 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1">{progression.map(([number, title, text]) => <article className="rounded-2xl border border-kbc-purple-100 p-6" key={number}><div className="flex justify-between"><b className="rounded-lg bg-kbc-purple-950 px-3 py-2 text-xs text-white">{number}</b><span className="text-[10px] font-bold uppercase tracking-wider text-kbc-purple-600">Stage {number}</span></div><h3 className="mt-8 text-xl">{title}</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">{text}</p></article>)}<article className="rounded-2xl border border-kbc-purple-100 bg-kbc-gold-50 p-6"><span className="text-[10px] font-bold uppercase text-kbc-purple-600">Example public-sector impact</span><h3 className="mt-8 text-xl">From fragmented reporting to defensible programme oversight.</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">An illustrative scenario showing how integrated controls can improve visibility across delivery partners and governance forums.</p></article></div></div></section>

    <section className={`${section} bg-kbc-gold-50`}><div className={shell}><div className="max-w-[780px]"><p className={eyebrow}>Employer journey</p><h2 className={heading}>Learn, apply, assure and evidence.</h2><p className="mt-5 text-kbc-purple-700">Employees should leave the programme with more than knowledge. They build practical evidence that can be reviewed, scrutinised and used inside the organisation.</p></div><div className="mt-12 grid grid-cols-2 overflow-hidden rounded-2xl bg-white shadow-lg max-[800px]:grid-cols-1"><img className="h-[560px] w-full object-cover" src="/assets/images/sectors/public-sector-employer-journey.jpg" alt="Public-sector employer and programme leadership meeting" /><div className="flex flex-col justify-center p-10"><p className={eyebrow}>Employer journey</p><h3 className="text-[clamp(36px,4vw,54px)] leading-[1.03]">A clear route from capability need to independent assessment.</h3><p className="mt-5 text-sm text-kbc-purple-700">The employer, learner and Kent Business College agree the role, development need, learning plan and evidence approach before enrolment.</p></div></div><div className="grid grid-cols-4 gap-3 pt-4 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1">{journey.map(([number, title, text]) => <article className="rounded-xl bg-white p-5" key={number}><b className="text-xs text-kbc-purple-600">{number}</b><h3 className="mt-4 text-base">{title}</h3><p className="mt-2 text-xs text-kbc-purple-700">{text}</p></article>)}</div></div></section>

    <section className={section}><div className={`${shell} max-w-[1040px]`}><p className={eyebrow}>Example public-sector impact scenario</p><h2 className={`${heading} max-w-[800px]`}>From fragmented reporting to defensible programme oversight.</h2><p className="mt-5 max-w-[760px] text-kbc-purple-700">A learner applies integrated controls to improve visibility across delivery partners, governance forums and approved programme baselines.</p><p className="mt-3 text-xs text-kbc-purple-600">This is an illustrative scenario. Replace it with approved and verifiable employer evidence before publication.</p><div className="mt-10 grid grid-cols-2 gap-5 max-[700px]:grid-cols-1">{[["01", "Challenge", "Milestones, dependencies, risks and supplier updates were held in different formats, limiting confidence in the programme view."], ["02", "Workplace application", "The learner established common data definitions, a controlled reporting cycle, clearer ownership and an integrated decision log."]].map(([number, title, text]) => <article className="flex min-h-64 flex-col rounded-2xl border border-kbc-purple-100 p-7 shadow-sm" key={number}><b className="font-['Source_Serif_4',Georgia,serif] text-5xl text-kbc-purple-600">{number}</b><h3 className="mt-2 text-xl">{title}</h3><p className="mt-auto border-t border-kbc-purple-100 pt-5 text-xs leading-5 text-kbc-purple-700">{text}</p></article>)}</div></div></section>

    <section className={`${section} bg-kbc-purple-950 text-white`}><div className={shell}><div className="max-w-[780px]"><p className={`${eyebrow} !text-kbc-gold-500`}>Apprenticeship funding</p><h2 className={`${heading} text-white`}>Use the right funding route for the right employee.</h2><p className="mt-5 text-white/65">Kent Business College reviews the employer, learner, role, programme and prior-learning position before confirming the available route.</p></div><div className="mt-12 grid grid-cols-[1.25fr_.75fr] gap-5 max-[800px]:grid-cols-1"><article className="rounded-2xl bg-white p-8 text-kbc-purple-950"><h3 className="text-3xl">Apprenticeship funding</h3><div className="mt-6 grid grid-cols-2 gap-4 max-[520px]:grid-cols-1">{[["Levy-funded employers", "Eligible organisations may use available apprenticeship-service funds for approved training and assessment."], ["Transfers and co-investment", "Current rules and circumstances may allow levy transfers or government co-investment."], ["Limited funded places", "Places or funding arrangements remain subject to availability and written confirmation."], ["Employer responsibilities", "Employers support learning activity, workplace application, evidence opportunities and progress reviews."]].map(([title, text]) => <div className="rounded-xl bg-kbc-purple-50 p-5" key={title}><b className="text-sm">{title}</b><p className="mt-2 text-xs text-kbc-purple-700">{text}</p></div>)}</div></article><div className="grid gap-5"><article className="rounded-2xl border-l-4 border-kbc-gold-500 bg-kbc-purple-900 p-7"><h3 className="text-xl text-white">Use apprenticeship funding</h3><p className="mt-3 text-sm text-white/65">Levy, transfer or co-investment routes may apply.</p></article><article className="rounded-2xl border-l-4 border-kbc-gold-500 bg-kbc-purple-900 p-7"><h3 className="text-xl text-white">Request a funding review</h3><p className="mt-3 text-sm text-white/65">Limited funded places may be available for eligible public-sector employers and employees.</p><NavigationButton className="mt-6" to="/book-session" variant="projectControls">Check employer eligibility</NavigationButton></article></div></div><p className="mt-6 text-xs text-white/55">“Fully funded” is not automatic. Funding depends on current government rules, employer and learner circumstances, programme eligibility, prior learning, available allocation and the funding-band maximum.</p></div></section>

    <section className={`${section} bg-kbc-gold-50`} id="career-guide"><div className={`${shell} grid grid-cols-[0.65fr_1.35fr] items-center gap-14 max-[800px]:grid-cols-1`}><div className="overflow-hidden rounded-2xl bg-kbc-purple-950 p-5"><img className="h-[390px] w-full rounded-xl object-cover" src="/assets/images/sectors/public-sector-employer-journey.jpg" alt="Public-Sector Project Controls Career and Interview Guide" /></div><div><p className={eyebrow}>Free 2026 career resource</p><h2 className={heading}>Public-Sector Project Controls Career and Interview Guide.</h2><p className="mt-5 text-kbc-purple-700">Explore role progression, responsibilities, salary benchmarks, public-project governance context and senior interview themes.</p><div className="mt-7 grid grid-cols-2 gap-3 max-[520px]:grid-cols-1">{["Project-controls role progression", "Planning, cost, risk and reporting", "Public-sector governance frameworks", "Senior interview preparation"].map((item) => <div className="flex items-center gap-3 rounded-xl bg-white p-4 text-sm shadow-sm" key={item}><Check className="h-4 w-4 text-kbc-purple-600" />{item}</div>)}</div><NavigationButton className="mt-7" to="/book-session">Discuss an apprenticeship pathway</NavigationButton></div></div></section>

    <section className={`${section} bg-kbc-purple-50`}><div className={`${shell} max-w-[900px]`}><div className="text-center"><p className={`${eyebrow} justify-center before:hidden`}>Employer questions</p><h2 className={heading}>Questions before you enquire.</h2></div><div className="mt-10 grid gap-3">{faqs.map(([question, answer]) => <article className="overflow-hidden rounded-xl border border-kbc-purple-100 bg-white" key={question}><button aria-expanded={openFaq === question} className="flex w-full items-center justify-between gap-5 p-5 text-left text-sm font-bold" onClick={() => setOpenFaq(openFaq === question ? null : question)} type="button">{question}<ChevronDown className={`h-5 w-5 shrink-0 text-kbc-purple-600 transition-transform ${openFaq === question ? "rotate-180" : ""}`} /></button>{openFaq === question && <p className="border-t border-kbc-purple-100 px-5 py-5 text-sm text-kbc-purple-700">{answer}</p>}</article>)}</div></div></section>

    <section className="bg-gradient-to-br from-kbc-purple-950 via-kbc-purple-900 to-kbc-purple-800 py-24 text-center text-white"><div className={`${shell} flex flex-col items-center`}><p className="text-[10px] font-bold uppercase tracking-[.17em] text-kbc-gold-500">Develop accountable project capability</p><h2 className={`${heading} mt-5 max-w-[900px] text-white`}>Build project teams that can plan, control and explain delivery with confidence.</h2><p className="mt-5 max-w-[720px] text-white/65">Speak with Kent Business College about employee roles, suitable apprenticeship routes, funding eligibility and the next available cohort.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><NavigationButton to="/book-session" variant="projectControls">Book an employer capability review</NavigationButton><NavigationButton to="/eligibility" variant="projectControlsInverse">Check employer eligibility</NavigationButton></div></div></section>
  </div>;
}
