# Generated by Django 5.2.16 on 2026-08-04 12:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X')], db_index=True, max_length=20)),
                ('source_id', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('url', models.URLField(validators=[apps.core.validators.validate_https_url])),
                ('platform_published_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-platform_published_at'],
            },
        ),
    ]
