# Generated by Django 5.2.16 on 2026-08-24

import apps.core.validators
from django.db import migrations, models


def migrate_existing_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    used_eventbrite_ids = set(
        Event.objects.exclude(eventbrite_id__isnull=True).values_list("eventbrite_id", flat=True)
    )
    for event in Event.objects.all().iterator():
        event.title = event.title[:220]
        event.venue_name = event.location[:220]
        event.location = event.address[:220]
        event.details_content = {"summary": event.summary, "source": "legacy"}
        event.is_published = event.status == "published"
        event.status = "live" if event.status == "published" else event.status
        legacy_id = event.legacy_source_id.removeprefix("eventbrite:")
        if event.legacy_source_id.startswith("eventbrite:") and legacy_id not in used_eventbrite_ids:
            event.eventbrite_id = legacy_id[:64]
            used_eventbrite_ids.add(event.eventbrite_id)
        event.save(
            update_fields=[
                "title",
                "venue_name",
                "location",
                "details_content",
                "is_published",
                "status",
                "eventbrite_id",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["starts_at", "title"]},
        ),
        migrations.RemoveConstraint(
            model_name="event",
            name="event_end_after_start",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_status_d5561c_idx",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start_at",
            new_name="starts_at",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="end_at",
            new_name="ends_at",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="booking_url",
            new_name="eventbrite_url",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="is_online",
            new_name="is_online_event",
        ),
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="details_content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(blank=True, default="Event", max_length=40),
        ),
        migrations.AddField(
            model_name="event",
            name="eventbrite_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="image_thumbnail_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_hidden_on_site",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="max_tickets_per_registration",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_opens_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_title",
            field=models.CharField(blank=True, default="Register for this event", max_length=120),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_name",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.RunPython(migrate_existing_events, migrations.RunPython.noop),
        migrations.RemoveField(model_name="event", name="address"),
        migrations.RemoveField(model_name="event", name="categories"),
        migrations.RemoveField(model_name="event", name="created_by"),
        migrations.RemoveField(model_name="event", name="image"),
        migrations.RemoveField(model_name="event", name="is_cancelled"),
        migrations.RemoveField(model_name="event", name="legacy_source_id"),
        migrations.RemoveField(model_name="event", name="published_at"),
        migrations.RemoveField(model_name="event", name="summary"),
        migrations.RemoveField(model_name="event", name="updated_by"),
        migrations.AlterField(
            model_name="event",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="eventbrite_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                validators=[apps.core.validators.validate_external_booking_url],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(blank=True, default="draft", max_length=32),
        ),
        migrations.AlterField(
            model_name="event",
            name="timezone",
            field=models.CharField(default="Europe/London", max_length=64),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=220),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type", "starts_at"], name="events_even_event_t_3fa0e1_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["eventbrite_id"], name="events_even_eventbr_b0f256_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["is_published", "starts_at"], name="events_even_is_publ_415ff6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["slug"], name="events_even_slug_30eb0f_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gte", models.F("starts_at")),
                    _connector="OR",
                ),
                name="event_ends_at_gte_starts_at",
            ),
        ),
    ]
