# Generated by Django 5.2.16 on 2026-09-08 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('page', models.CharField(db_index=True, max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('published_content', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('published_content', models.JSONField(null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cms.contententry')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(fields=('page', 'section'), name='cms_unique_page_section'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('entry', 'version'), name='cms_unique_revision'),
        ),
    ]
