"""One-time Home import. Runtime content is stored only in Neon JSONField columns.

Frozen source snapshot: existing React Home, 2026-09-08. Never re-seeds on startup.
Existing entries are preserved, including all editorial changes.
"""
from django.db import migrations
from django.utils import timezone

INITIAL_HOME = [{'key': 'home.metadata',
  'page': 'home',
  'section': 'metadata',
  'title': 'Page metadata',
  'content': {'title': 'Kent Business College | Chartered Project, Chartered Marketing, CIM, PMI and APMG Courses',
              'description': 'Kent Business College delivers fully funded professional courses, apprenticeships '
                             'and employer-supported programmes in project management, Chartered Marketing, CIM, '
                             'PMI and APMG qualifications.'},
  'sort_order': 0},
 {'key': 'home.hero',
  'page': 'home',
  'section': 'hero',
  'title': 'Hero',
  'sort_order': 1,
  'content': {'copy': {'poster': '/assets/images/figma-home/hero-group.png',
                       'src': '/assets/video/home-hero.webm',
                       'src2': '/assets/video/home-hero.mp4',
                       'paragraph': 'For working professionals',
                       'heading': 'Build skills that move your',
                       'text': 'career forward.',
                       'paragraph2': 'Learn while you work through role relevant apprenticeships, specialist '
                                     'coaching and pathways towards recognised professional qualifications.',
                       'to': '#programmes',
                       'linkLabel': 'Find your programme',
                       'to2': '/funding-eligibility',
                       'linkLabel2': 'Check your eligibility',
                       'text2': 'Learn in your role',
                       'text3': 'Apply new capability in the workplace',
                       'text4': 'Professional pathways',
                       'text5': 'Progress towards recognised qualifications',
                       'text6': 'Dedicated support',
                       'text7': 'Coaching, reviews and assessment preparation',
                       'text8': 'Professional domains',
                       'text9': 'Project · Controls · Marketing · Leadership',
                       'src3': '/assets/images/figma-home/hero-group.png',
                       'alt': 'Kent Business College professional learning event',
                       'text10': 'Pathway design',
                       'text11': 'Funding → learning → professional progression'}}},
 {'key': 'home.trusted',
  'page': 'home',
  'section': 'trusted',
  'title': 'Trusted organisations',
  'sort_order': 2,
  'content': {'trustedOrganisationLogos': [{'name': 'Crazy Bear',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/4595895af96c4c4d9218658cad3c3944.webp'},
                                           {'name': 'University of Lincoln',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/347e5d11627e434882f84a1935eaa5b2.webp'},
                                           {'name': 'BMT',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/d41fcca69ced4ee19edf5f3602d7bba4.webp'},
                                           {'name': 'Nolan Business Solutions',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/53ea37c179fe4ccbba9069eb100845a8.webp'},
                                           {'name': 'Network Rail',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/b8214283f7614be988da19816c56a574.webp'},
                                           {'name': 'Liverpool City Council',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/f5447dee04af4c6099e225dd30c2b827.webp'},
                                           {'name': 'Wincanton',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/4c25df04ce73469b88478cdc5c46e105.webp'},
                                           {'name': 'West Lancashire College',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/ff3503a090c3485da3f2d6a86f969d86.webp'},
                                           {'name': 'Watts',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/b26010f18a3348fe92b8dbce19891671.webp'},
                                           {'name': 'London School of Economics and Political Science',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/e627bc942684469b9dd178b3406c7bec.webp'},
                                           {'name': 'Lolly',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/6fcac89d80884b38a37f1953d78f7f61.webp'},
                                           {'name': 'Judytia',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/84aa2073f38f4633a76bb23595345096.webp'},
                                           {'name': 'Partner organisation 13',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/5dd67e4ddf6e4e02b81a661ef5551836.webp'},
                                           {'name': 'Partner organisation 14',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/7e9051fb549347e9a6212c864edc42b1.webp'},
                                           {'name': 'Partner organisation 15',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/5105df9217d045eba0172fd4cc9dbb6d.webp'},
                                           {'name': 'Partner organisation 16',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/7cea1542235244e08e459d0e7ee6ab6d.webp'},
                                           {'name': 'Partner organisation 17',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/a0159d25123a42c7b5f0d74a45034539.webp'},
                                           {'name': 'Partner organisation 18',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/0a13aaaea52c4be89a25d1b7fca46826.webp'},
                                           {'name': 'Partner organisation 19',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/2bbe1002ee184df49500182d928c2f2b.webp'},
                                           {'name': 'Partner organisation 20',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/61cab00535584d48be4866a63fdb3fc3.webp'},
                                           {'name': 'Partner organisation 21',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/be8a4a24f484456eac6e5fd1ad14e719.webp'},
                                           {'name': 'Partner organisation 22',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/a5bf37dd21ec49ce9c5401526bc0cd67.webp'},
                                           {'name': 'Partner organisation 23',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/b0153e509a2e4c1eba48d2a60c9740d2.webp'},
                                           {'name': 'Partner organisation 24',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/e8bf62c676b549d2b682f97d10e503ab.webp'},
                                           {'name': 'Partner organisation 25',
                                            'image': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/34ead1b2cc0c4d54863e94e1443ab705.webp'}],
              'copy': {'eyebrow': 'Trusted by',
                       'title': 'Professionals from leading organisations',
                       'description': 'Employees from respected organisations choose KBC to strengthen practical, '
                                      'role-ready capability.',
                       'to': '/our-partners',
                       'linkLabel': 'View all partner logos '}}},
 {'key': 'home.development',
  'page': 'home',
  'section': 'development',
  'title': 'Development pathways',
  'sort_order': 3,
  'content': {'audienceContent': {'professionals': {'cards': [{'eyebrow': '01',
                                                               'title': 'Specialist Knowledge',
                                                               'description': 'Develop role-relevant professional '
                                                                              'capability',
                                                               'points': ['Role-relevant apprenticeships',
                                                                          'Specialist colleges and professional '
                                                                          'programmes',
                                                                          'Learning matched to your '
                                                                          'responsibilities and goals']},
                                                              {'eyebrow': '02',
                                                               'title': 'Expert Learning',
                                                               'description': 'Learn with experienced '
                                                                              'professionals',
                                                               'points': ['Live interactive learning',
                                                                          'Dedicated coaching and one-to-one '
                                                                          'tutoring',
                                                                          'Session recordings and catch-up '
                                                                          'support']},
                                                              {'eyebrow': '03',
                                                               'title': 'Workplace Evidence',
                                                               'description': 'Apply development through real '
                                                                              'work',
                                                               'points': ['Workplace activities connected to your '
                                                                          'job',
                                                                          'Progress reviews with your employer '
                                                                          'and coach',
                                                                          'Evidence building and assessment '
                                                                          'preparation']},
                                                              {'eyebrow': '04',
                                                               'title': 'Professional Progression',
                                                               'description': 'Build evidence for greater '
                                                                              'responsibility',
                                                               'points': ['Recognised professional qualifications',
                                                                          'Professional memberships and '
                                                                          'communities',
                                                                          'Pathways towards greater '
                                                                          'responsibility and chartered '
                                                                          'progression'],
                                                               'note': 'Subject to programme eligibility and '
                                                                       'relevant professional-body '
                                                                       'requirements.'}],
                                                    'image': '/assets/images/professional-pathway-training.png',
                                                    'imageAlt': 'A professional learning project management with '
                                                                'an expert trainer',
                                                    'stats': [{'value': 'Specialist',
                                                               'label': 'role-relevant knowledge'},
                                                              {'value': 'Expert-led',
                                                               'label': 'professional learning'},
                                                              {'value': 'Workplace', 'label': 'applied evidence'},
                                                              {'value': 'Progression',
                                                               'label': 'greater responsibility'}],
                                                    'primaryLabel': 'Explore Professional Programmes',
                                                    'primaryTo': '/programmes',
                                                    'secondaryLabel': 'Find Your Pathway',
                                                    'secondaryTo': '/learners'},
                                  'employers': {'cards': [{'eyebrow': '01 - Government funded',
                                                           'title': 'DfE Fully Funded',
                                                           'description': 'Complete professional programmes for '
                                                                          'eligible employers and employees.',
                                                           'linkLabel': 'View funded programmes',
                                                           'to': '/programmes'},
                                                          {'eyebrow': '02 - IPC bursary',
                                                           'title': 'IPC Bursary',
                                                           'emphasis': '50%',
                                                           'emphasisGold': False,
                                                           'description': 'Commercial specialist modules with 50% '
                                                                          'bursary support on selected options.',
                                                           'detail': 'Selected specialist modules',
                                                           'linkLabel': 'Explore 50% supported modules',
                                                           'to': '/programmes'},
                                                          {'eyebrow': '03 - Enhanced IPC bursary',
                                                           'title': 'IPC Bursary',
                                                           'emphasis': '75%',
                                                           'emphasisGold': True,
                                                           'description': 'Enhanced bursary support for selected '
                                                                          'specialist modules.',
                                                           'detail': 'Selected specialist modules',
                                                           'linkLabel': 'Explore 75% supported modules',
                                                           'to': '/programmes'},
                                                          {'eyebrow': '04 - Flexible professional development',
                                                           'title': 'Flexible Development',
                                                           'description': 'Choose one module or combine several '
                                                                          "around your organisation's capability "
                                                                          'needs.',
                                                           'linkLabel': 'Build your development mix',
                                                           'to': '/book-session'}],
                                                'image': '/assets/images/professional-development-employers.png',
                                                'imageAlt': 'Experienced professionals developing an organisation '
                                                            'strategy together',
                                                'stats': [{'value': 'DfE', 'label': 'fully funded route'},
                                                          {'value': '50%', 'label': 'IPC bursary support'},
                                                          {'value': '75%', 'label': 'enhanced IPC bursary'},
                                                          {'value': 'Flexible', 'label': 'professional modules'}],
                                                'primaryLabel': 'Explore Employer Programmes',
                                                'primaryTo': '/programmes',
                                                'secondaryLabel': 'Check Eligibility & Funding',
                                                'secondaryTo': '/eligibility'}},
              'copy': {'eyebrow': 'Choose your pathway',
                       'title': 'Professional development built around real work',
                       'description': 'Whether you are developing your own capability or building capability '
                                      'across your organisation, Kent Business College helps you find the right '
                                      'professional route.',
                       'note': 'Working professionals',
                       'text': 'For Professionals',
                       'text2': 'Professional development & progression',
                       'note2': 'Organisations',
                       'text3': 'For Employers',
                       'text4': 'Workforce capability · Funding & bursaries',
                       'paragraph': 'DfE funding is subject to eligibility, employer participation and funding '
                                    'confirmation. IPC bursary support applies to selected commercial modules and '
                                    'is subject to module eligibility, approval and availability.'}}},
 {'key': 'home.colleges',
  'page': 'home',
  'section': 'colleges',
  'title': 'Specialist colleges',
  'sort_order': 4,
  'content': {'colleges': [{'number': '01',
                            'category': 'Project Management',
                            'title': 'Deliver complex work with greater confidence.',
                            'tags': ['Planning', 'Stakeholders', 'Risk', 'Governance'],
                            'cta': 'Explore Project Management',
                            'href': '/college-of-project-controls-and-project-management',
                            'tone': 'navy'},
                           {'number': '02',
                            'category': 'Project Controls',
                            'title': 'Turn complexity into better decisions.',
                            'tags': ['Schedule', 'Cost', 'Risk', 'Forecasting'],
                            'cta': 'Explore Project Controls',
                            'href': '/college-of-project-controls-and-project-management',
                            'tone': 'teal'},
                           {'number': '03',
                            'category': 'Marketing',
                            'title': 'Turn customer insight into commercial growth.',
                            'tags': ['Strategy', 'Digital', 'Customer', 'Performance'],
                            'cta': 'Explore Marketing',
                            'href': '/college-of-marketing',
                            'tone': 'coral'},
                           {'number': '04',
                            'category': 'Leadership',
                            'title': 'Turn responsibility into strategic influence.',
                            'tags': ['Strategy', 'People', 'Change', 'Decision-making'],
                            'cta': 'Explore Leadership',
                            'href': '/college-of-leadership',
                            'tone': 'plum'}],
              'copy': {'eyebrow': 'Our specialist colleges',
                       'title': 'Choose the capability you want to build',
                       'description': 'Four specialist colleges. One professional institution — built around the '
                                      'capability professionals and organisations need at work.'}}},
 {'key': 'home.programmes',
  'page': 'home',
  'section': 'programmes',
  'title': 'Featured programmes',
  'sort_order': 5,
  'content': {'programmes': [{'number': '01',
                              'level': 'Level 6',
                              'category': 'Project Controls',
                              'title': 'Project Controls Professional',
                              'description': 'Master schedule, cost, risk and forecasting to keep complex '
                                             'projects on track and under control.',
                              'href': '/project-controls-professional-level-6',
                              'tone': 'controls'},
                             {'number': '02',
                              'level': 'Level 4',
                              'category': 'Project Management',
                              'title': 'Associate Project Manager',
                              'description': 'Build the planning, stakeholder and delivery skills to lead '
                                             'projects with real confidence.',
                              'href': '/associate-project-manager-level-4',
                              'tone': 'management'},
                             {'number': '03',
                              'level': 'Level 4',
                              'category': 'Marketing',
                              'title': 'Marketing Executive',
                              'description': 'Turn customer insight into campaigns that deliver measurable '
                                             'commercial growth.',
                              'href': '/marketing-executive-level-4',
                              'tone': 'marketing'},
                             {'number': '04',
                              'level': 'Level 6',
                              'category': 'Marketing',
                              'title': 'Marketing Manager',
                              'description': 'Lead marketing strategy and performance to shape brand direction '
                                             'and business results.',
                              'href': '/marketing-manager-level-6',
                              'tone': 'marketing'}],
              'copy': {'eyebrow': 'Featured programmes',
                       'title': 'Professional development for real responsibility',
                       'text': 'Explore programme',
                       'to': '/programmes',
                       'linkLabel': 'View all programmes '}}},
 {'key': 'home.applied',
  'page': 'home',
  'section': 'applied',
  'title': 'Applied learning',
  'sort_order': 6,
  'content': {'journeySteps': [{'number': '01',
                                'title': 'Check your fit',
                                'description': 'Confirm your current role, experience, eligibility and preferred '
                                               'professional direction.'},
                               {'number': '02',
                                'title': 'Choose the right programme',
                                'description': 'Match your responsibilities and goals with the appropriate '
                                               'apprenticeship level.'},
                               {'number': '03',
                                'title': 'Learn and apply',
                                'description': 'Combine live learning, coaching and workplace activities '
                                               'connected to your job.'},
                               {'number': '04',
                                'title': 'Demonstrate progress',
                                'description': 'Build evidence, prepare for assessment and continue towards '
                                               'professional recognition.'}],
              'copy': {'eyebrow': 'Applied learning',
                       'title': 'Learn with experts Apply it at work.',
                       'description': 'A clear journey from application to progression.'}}},
 {'key': 'home.experience',
  'page': 'home',
  'section': 'experience',
  'title': 'The KBC experience',
  'sort_order': 7,
  'content': {'qualifications': ['CIM', 'APM', 'PMI', 'APMG', 'ChPP', 'IPC', 'ICostE', 'CaSA'],
              'fundBenefits': ['Professional exam fees',
                               'Registration fees',
                               'APM ChPP application & preparation support where applicable',
                               'Workshop travel',
                               'Graduation rewards',
                               'No hidden costs',
                               'Professional memberships',
                               'Relevant professional exam support',
                               'ICostE / Certified Professional Cost Engineer pathway support where applicable',
                               'Graduation ceremony',
                               'Laptop prize where applicable'],
              'supportBenefits': ['Live interactive learning',
                                  'Session recordings',
                                  'Catch-up support',
                                  'One-to-one tutoring'],
              'eventBenefits': ['KBC professional Masterclasses',
                                'London Masterclass events',
                                'Networking opportunities',
                                'Optional UK in-person workshops',
                                'Professional community'],
              'workshopLocations': ['London', 'Kent', 'Nottingham', 'Derby', 'Birmingham', 'York', 'Manchester'],
              'copy': {'eyebrow': 'Why Kent Business College',
                       'title': 'The programme is only part of the experience.',
                       'description': 'Kent Business College combines workplace-focused professional learning '
                                      'with recognised qualifications, specialist support, professional events '
                                      'and additional investment designed to extend development beyond the core '
                                      'programme.',
                       'text': 'More built into your professional development.',
                       'src': '/assets/images/figma-home/kbc-experience-networking.png',
                       'alt': 'Women professionals networking at an evening event',
                       'text2': 'The KBC experience',
                       'heading': 'Development that extends beyond the core programme.',
                       'to': '/events',
                       'linkLabel': 'Explore the full experience',
                       'text3': 'Professional qualifications & pathways',
                       'heading2': 'Go beyond programme completion.',
                       'paragraph': 'Selected programmes include support towards relevant professional '
                                    'qualifications, memberships, registration and examination costs.',
                       'src2': '/assets/logos/kbc-logo-figma.png',
                       'alt2': 'Kent Business College',
                       'text4': 'Kent Business College Fund',
                       'heading3': 'Additional investment from KBC',
                       'paragraph2': 'Separate from Department for Education apprenticeship funding.',
                       'note': 'Selected KBC Fund benefits are limited to the first 30 eligible learners per '
                               'applicable cohort where specified.',
                       'to2': '/funding-eligibility#kbc-fund-details',
                       'linkLabel2': 'Discover the KBC Fund',
                       'src3': '/assets/logos/kbc-logo-figma.png',
                       'alt3': 'Kent Business College',
                       'text5': 'Extended tutoring & professional guidance',
                       'heading4': 'Support that fits your working week',
                       'text6': '7 days a week',
                       'text7': 'Until 9:00 PM',
                       'text8': 'Professional Masterclasses & events',
                       'heading5': 'Learn and network with professionals',
                       'src4': '/assets/images/learner-home/masterclass.webp',
                       'alt4': 'Professionals attending a KBC Masterclass',
                       'text9': 'London Masterclasses',
                       'text10': 'Hosted at the Marble Arch Hotel three times a year — bringing together '
                                 'learners, employers, line managers and training leaders.',
                       'text11': 'Travel support & professional experiences',
                       'heading6': 'Reach the experiences that matter',
                       'text12': 'Travel support for applicable workshops',
                       'text13': 'Travel costs for KBC Masterclasses where included',
                       'text14': 'Workshop locations',
                       'text15': 'Recognition, graduation & further development',
                       'heading7': 'Recognition that extends your pathway',
                       'src5': '/assets/logos/kbc-crest.png',
                       'alt5': 'Kent Business College crest',
                       'text16': 'Graduation',
                       'text17': 'Rochester Cathedral and professional-body graduation where applicable',
                       'text18': 'Rewards & prizes',
                       'text19': 'Graduation rewards and laptop prize where applicable',
                       'src6': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/c49b55b4496342219ee90b7b048c7dc7.png',
                       'alt6': 'APM Recognised Assessment for the ChPP standard',
                       'text20': 'Further development',
                       'text21': 'Eligible Level 7 development and ChPP progression support',
                       'text22': 'Professional community',
                       'text23': 'Student Clubs Memberships · London · Kent · Manchester · Liverpool · Birmingham',
                       'paragraph3': ' Private health care insurance where included.',
                       'note2': 'Benefits vary by programme, eligibility, cohort and availability.',
                       'to3': '/about',
                       'linkLabel3': 'Discover Why KBC'}}},
 {'key': 'home.support',
  'page': 'home',
  'section': 'support',
  'title': 'Support throughout',
  'sort_order': 8,
  'content': {'supportItems': [{'title': 'Dedicated coaching',
                                'description': 'Regular guidance helps you connect learning to your '
                                               'responsibilities and maintain progress.',
                                'note': 'A coach connected to your professional role',
                                'icon': 'UserRoundCheck'},
                               {'title': 'Progress reviews',
                                'description': 'Structured reviews bring learner, employer and coach together '
                                               'around development priorities.',
                                'note': 'Learner, employer and coach aligned',
                                'icon': 'CalendarCheck2'},
                               {'title': 'Wellbeing support',
                                'description': 'Access guidance and support designed to help you manage learning '
                                               'alongside professional life.',
                                'icon': 'HeartHandshake'},
                               {'title': 'Assessment preparation',
                                'description': 'Build evidence and prepare confidently for end-point or external '
                                               'assessment requirements.',
                                'icon': 'ClipboardCheck'},
                               {'title': 'Professional community',
                                'description': 'Join masterclasses, events and networking opportunities with '
                                               'other working professionals.',
                                'icon': 'UsersRound'},
                               {'title': 'Career progression',
                                'description': 'Understand how your programme connects to qualifications, '
                                               'membership and future professional routes.',
                                'icon': 'ChartNoAxesColumnIncreasing'}],
              'journey': ['Start', 'Learn', 'Review', 'Evidence', 'Progress'],
              'copy': {'eyebrow': 'Support throughout',
                       'title': 'You are supported as a professional',
                       'description': 'KBC combines structured programme delivery with individual guidance and '
                                      'workplace-focused development.'}}},
 {'key': 'home.events',
  'page': 'home',
  'section': 'events',
  'title': 'Upcoming events',
  'content': {'eyebrow': 'Upcoming Events',
              'title': 'Upcoming events, all in one place.',
              'description': 'Explore the next workshops, information sessions and professional events from Kent '
                             'Business College.',
              'featuredActionLabel': 'Reserve your place',
              'viewAllLabel': 'View all events',
              'fallbackImages': ['/assets/images/figma-home/marketing-event.png',
                                 '/assets/images/figma-home/project-speaker.png',
                                 '/assets/images/figma-home/workplace-teaching.png']},
  'sort_order': 9},
 {'key': 'home.careers',
  'page': 'home',
  'section': 'careers',
  'title': 'Career outcomes',
  'sort_order': 10,
  'content': {'careerPaths': [{'id': 'project-leader',
                               'tab': 'Project Leader',
                               'role': 'Project Leader',
                               'roleDescription': 'Your current role or the next step you are working towards.',
                               'capability': 'Project Management',
                               'capabilityDescription': 'Lead the planning, stakeholder and delivery of projects '
                                                        'with greater confidence.',
                               'programmes': [{'title': 'Associate Project Manager',
                                               'level': 'Level 4',
                                               'href': '/associate-project-manager-level-4'}]},
                              {'id': 'project-controls-specialist',
                               'tab': 'Project Controls Specialist',
                               'role': 'Project Controls Specialist',
                               'roleDescription': 'Your current role or the next step you are working towards.',
                               'capability': 'Project Controls',
                               'capabilityDescription': 'Master schedule, cost, risk and forecasting for complex '
                                                        'project environments.',
                               'programmes': [{'title': 'Project Controls Professional',
                                               'level': 'Level 6',
                                               'href': '/college-of-project-controls-and-project-management'}]},
                              {'id': 'marketing-manager',
                               'tab': 'Marketing Manager',
                               'role': 'Marketing Manager',
                               'roleDescription': 'Your current role or the next step you are working towards.',
                               'capability': 'Marketing',
                               'capabilityDescription': 'Turn customer insight into measurable commercial growth '
                                                        'and strategic direction.',
                               'programmes': [{'title': 'Marketing Executive',
                                               'level': 'Level 4',
                                               'href': '/marketing-executive-level-4'},
                                              {'title': 'Marketing Manager',
                                               'level': 'Level 6',
                                               'href': '/marketing-manager-level-6'}]},
                              {'id': 'senior-leader',
                               'tab': 'Senior Leader',
                               'role': 'Senior Leader',
                               'roleDescription': 'Your current role or the next step you are working towards.',
                               'capability': 'Leadership',
                               'capabilityDescription': 'Strengthen strategic judgement, leadership and '
                                                        'organisational impact at a more senior level.',
                               'programmes': [{'title': 'Master of Business Administration',
                                               'level': 'Level 7',
                                               'href': '/mba-diploma-level-7'}]}],
              'copy': {'eyebrow': 'Choose your direction',
                       'title': 'Start with the career outcome',
                       'description': 'Select the role you hold or are moving towards, then see the capability '
                                      'and programme built around that next step.',
                       'text': 'Role',
                       'text2': 'Capability',
                       'text3': 'Programme',
                       'to': '/programmes',
                       'linkLabel': 'Compare programmes for your role'}}},
 {'key': 'home.progression',
  'page': 'home',
  'section': 'progression',
  'title': 'Progression pathway',
  'sort_order': 11,
  'content': {'pathwaySteps': [{'number': '01',
                                'title': 'Apprenticeship',
                                'description': 'Role-relevant development',
                                'tone': 'quiet'},
                               {'number': '02',
                                'title': 'Qualification',
                                'description': 'Professional study route',
                                'tone': 'primary'},
                               {'number': '03',
                                'title': 'Membership',
                                'description': 'Professional community',
                                'tone': 'primary'},
                               {'number': '04',
                                'title': 'Chartered pathway',
                                'description': 'Subject to body requirements',
                                'tone': 'outlined'}],
              'copy': {'eyebrow': 'Professional progression',
                       'title': 'Build a pathway beyond completion',
                       'description': 'Selected programmes connect apprenticeship and professional development '
                                      'with qualifications, professional communities and further progression '
                                      'opportunities.',
                       'text': 'Step',
                       'to': '/programmes',
                       'paragraph': 'Progress',
                       'paragraph2': 'Greater responsibility · Professional recognition · Further development',
                       'paragraph3': 'Professional membership, qualification and chartered progression remain '
                                     'subject to the requirements of the relevant professional body.'}}},
 {'key': 'home.recognition',
  'page': 'home',
  'section': 'recognition',
  'title': 'Recognition and standards',
  'sort_order': 12,
  'content': {'recognitionLogos': [{'name': 'Recognition partner 1',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/356aeb204f224be68e62727bcbbb1c75.webp'},
                                   {'name': 'Recognition partner 2',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/c2cd9e7a9c4842ab822c0aac16ffa061.webp'},
                                   {'name': 'Association for Project Management',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/bb930e8a6230490b850425c0f6643aab.webp'},
                                   {'name': 'Recognition partner 3',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/5c4f7558699844a28d0d1fbf308b7b25.webp'},
                                   {'name': 'Institute of Project Controls',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/cfc267af22a941a4bf58b79926482616.png'},
                                   {'name': 'Recognition partner 4',
                                    'src': 'https://jokdxsdbxorzciulkdyl.supabase.co/storage/v1/object/public/images/8ba3636c4a53491f86912fe3fa597438.webp'}],
              'copy': {'eyebrow': 'Recognition & standards',
                       'title': 'Recognised standards, strengthened by professional connections',
                       'description': 'Professional standards are built into the KBC learning experience through '
                                      'relevant qualifications, professional-body pathways and recognised '
                                      'programme frameworks.',
                       'paragraph': 'Qualifications, memberships, professional-body relationships and recognition '
                                    'vary by programme.'}}},
 {'key': 'home.testimonials',
  'page': 'home',
  'section': 'testimonials',
  'title': 'Learner testimonials',
  'content': {'items': [{'name': 'Gill Stoney',
                         'role': 'Workforce Scheduling Team Manager at St John Ambulance',
                         'image': '/assets/people/gill-stoney.webp',
                         'quote': 'It was really good to go through all the system elements, especially '
                                  'considering how confused we were and that we had all been together for nearly '
                                  'two weeks. If we had had this before the course started, it would have been '
                                  'much easier and far less stressful. Affan was very good at explaining the '
                                  'elements of the online system for recording our work and hours, and I now feel '
                                  'much more comfortable using it.'},
                        {'name': 'Andrew Hurll',
                         'role': 'Commercial Manager at SCA Group Limited',
                         'image': '/assets/people/andrew-hurll.webp',
                         'quote': 'I am currently studying on the Executive Marketing Manager Level 4 programme '
                                  'at Kent Business College. The course is very well organised and delivered, and '
                                  'the lecturers are engaging and friendly. I am thoroughly enjoying the content, '
                                  'and all materials and support are easily accessible. I am looking forward to '
                                  'completing the course and gaining my qualification.'},
                        {'name': 'Lauren Hiney',
                         'role': 'Digital marketing | Strategic marketing | B2B & B2C | Measuring metrics',
                         'image': '/assets/people/lauren-hiney.webp',
                         'quote': 'The team at Kent Business College has been extremely supportive. Since '
                                  'starting my diploma, I have received great advice, clear information, and '
                                  'excellent teaching from the team.'},
                        {'name': 'Alicia Mouskovias',
                         'role': 'Internal Sales and Marketing at 2B Heard and Sontronics',
                         'image': '/assets/people/alicia-mouskovias.webp',
                         'quote': 'I am really enjoying the Level 4 Marketing training with Kent Business '
                                  'College. The lectures, one-to-one tutor support, and online learning platforms '
                                  'have all been very helpful. The resources provided make it easy to stay on '
                                  'track, and the experience has been extremely positive for my career '
                                  'development.'},
                        {'name': 'Inga Lightley',
                         'role': 'Administrator & Marketing Professional, YouTube Creator, Property Investor',
                         'image': '/assets/people/inga-lightley.webp',
                         'quote': 'I am enjoying the Level 4 Executive Marketing programme at Kent Business '
                                  'College. The lecturers are knowledgeable and friendly, and I really enjoy the '
                                  'live sessions with high-quality slides and the option to rewatch recordings '
                                  'later. The additional quizzes also make the learning experience engaging and '
                                  'interactive.'},
                        {'name': 'Dawn Taylor',
                         'role': 'Head of Projects Roadchef',
                         'image': '/assets/people/dawn-taylor.webp',
                         'quote': 'For all project management professionals, I would highly recommend this '
                                  'course. I have been enrolled for over two years and have thoroughly enjoyed it '
                                  'while learning a great deal of relevant content. The lecturers are excellent, '
                                  'the cohort is incredibly supportive, and the fact that the programme is fully '
                                  'funded makes it a complete win-win.'},
                        {'name': 'Joanna Monika Jablonska',
                         'role': 'Project Control Professional Level 6',
                         'image': '/assets/people/joanna-monika-jablonska.webp',
                         'quote': 'Overall, my experience with the provider’s leadership and management has been '
                                  'very positive, with clear communication, good support, and effective programme '
                                  'delivery.'},
                        {'name': 'Giles Magee',
                         'role': 'Project Control Professional Level 6',
                         'image': '/assets/people/giles-magee.webp',
                         'quote': 'I have had little direct experience with the management or leadership, but '
                                  'from the brief interactions I have had relating to it, the provider seems well '
                                  'organised and is very supportive of their learners.'}],
              'eyebrow': 'Learner testimonials',
              'backgroundImage': '/assets/images/figma-home/marketing-event.png'},
  'sort_order': 13},
 {'key': 'home.funding',
  'page': 'home',
  'section': 'funding',
  'title': 'Funding guidance',
  'sort_order': 14,
  'content': {'copy': {'paragraph': 'Your next step',
                       'heading': 'Ready to build what comes',
                       'heading2': 'next?',
                       'paragraph2': 'Find the professional programme, funding route or development option that '
                                     'fits you or your organisation.',
                       'note': 'For professionals and employers · Funding subject to eligibility and availability',
                       'to': '#programmes',
                       'linkLabel': 'Find your programme',
                       'to2': '/book-session',
                       'linkLabel2': 'Book an information session',
                       'to3': '/eligibility',
                       'linkLabel3': 'Check eligibility & funding'}}}]

def seed_home(apps, schema_editor):
    Entry = apps.get_model("cms", "ContentEntry")
    Revision = apps.get_model("cms", "ContentRevision")
    alias = schema_editor.connection.alias
    for row in INITIAL_HOME:
        entry, created = Entry.objects.using(alias).get_or_create(
            key=row["key"], defaults={
                **{k: v for k, v in row.items() if k != "key"},
                "published_content": row["content"], "published_at": timezone.now(),
            },
        )
        if created:
            Revision.objects.using(alias).create(
                entry=entry, version=1, action="import", content=entry.content,
                published_content=entry.published_content, is_active=True,
            )


class Migration(migrations.Migration):
    dependencies = [("cms", "0001_initial")]
    operations = [migrations.RunPython(seed_home, migrations.RunPython.noop)]
