# Generated by Django 5.2.16 on 2026-09-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_import_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['group', 'title'],
            },
        ),
        migrations.AddField(
            model_name='contententry',
            name='content_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cms.contentpage'),
        ),
    ]
