import { ArrowRight, Check, ChevronDown, Factory, Gauge, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { NavigationButton } from "@/components/navigation";
import { RouteMeta } from "@/components/seo/RouteMeta";

const shell = "mx-auto w-[calc(100%-2.5rem)] max-w-[1240px] max-[600px]:w-[calc(100%-1.75rem)]";
const section = "py-28 max-[600px]:py-20";
const heading = "font-['Source_Serif_4',Georgia,serif] text-[clamp(44px,5vw,68px)] font-semibold leading-[1.01] tracking-[-.045em] text-kbc-purple-950";
const eyebrow = "mb-4 text-[11px] font-bold uppercase tracking-[.16em] text-kbc-purple-600";

const pathways = [
  ["6-credit pathway", "Operational Pathway", "For emerging and developing project-controls professionals working close to live delivery.", ["PMP · 2 credits", "AI in Project Controls · 1 credit", "Choose 3 specialist credits"]],
  ["6-credit pathway", "Strategic Pathway", "For senior managers, programme professionals and controls leaders influencing portfolio decisions.", ["PMP · 2 credits", "AI in Project Controls · 1 credit", "Choose 3 strategic credits"]],
  ["6-credit pathway", "Chartered Pathway", "For experienced PMO and project-controls professionals preparing senior evidence and progression.", ["Certified PMO Professional L6 · 4", "AI in Project Controls · 1", "Choose 1 specialist credit"]],
  ["4-credit pathway", "PMO Certified", "A focused route for PMO governance, standards, operating models and organisational control.", ["Certified PMO Professional L6", "PMO foundations and operating model", "Evidence-led professional practice"]],
];

const creditOptions = [
  ["PMP Preparation and Professional Development", "Mandatory core", "2 credits"],
  ["AI in Project Controls Certificate", "Mandatory core", "1 credit"],
  ["PMI Scheduling Professional · PMI-SP", "Specialist option", "1 credit"],
  ["Earned Value Management · EVM", "Specialist option", "1 credit"],
  ["Risk Management", "Specialist option", "1 credit"],
  ["Project Planning & Control · PPC", "Specialist option", "1 credit"],
];

const outputs = [
  ["Integrated engineering baseline", "Requirements, scope, work breakdown, interfaces, design maturity, schedule and cost structures."],
  ["Design maturity and requirements register", "Traceability, approvals, technical decisions, interfaces and configuration status."],
  ["Integrated schedule and resource plan", "Engineering, procurement, tooling, testing, production and launch dependencies."],
  ["EVM and cost forecast dashboard", "Performance indicators, variance analysis, estimate confidence and forecast interpretation."],
  ["Risk, FMEA and change register", "Technical, quality, supplier, safety, commercial and configuration exposure."],
  ["Production-readiness and assurance pack", "Verification evidence, readiness gates, recommendations and senior decision points."],
];

const roles = [
  ["01", "Project Controls Engineer", "Integrate scope, planning, cost, risk, change and engineering performance."],
  ["02", "Planning & Scheduling Engineer", "Build and assure schedules across engineering, sourcing, testing and production."],
  ["03", "Cost / Value Engineer", "Control estimates, forecasts, value decisions and commercial exposure."],
  ["04", "Engineering Programme Manager", "Coordinate technical teams, suppliers, milestones and delivery outcomes."],
  ["05", "Engineering PMO Manager", "Establish governance, reporting standards and portfolio visibility."],
  ["06", "Systems Integration & Assurance Lead", "Challenge interfaces, readiness, evidence and confidence in delivery plans."],
];

const faqs = [
  ["Who is this engineering sector page for?", "It is for engineering and advanced-manufacturing employers and professionals working across project controls, planning, scheduling, cost, risk, PMO, systems integration, product development, production readiness, quality, assurance and complex programme delivery."],
  ["Are the six-credit pathways fully funded?", "Eligible employees may be able to access a six-credit pathway through the DfE Funded Route, subject to all applicable rules and written confirmation."],
  ["What is included in the Operational Pathway?", "The route combines PMP preparation, the AI in Project Controls Certificate and three specialist credits selected for operational responsibility."],
  ["How is the Strategic Pathway different?", "It is designed for senior professionals influencing programme, portfolio, governance and organisational decisions."],
  ["Does the Chartered Pathway guarantee ChPP?", "No. Professional recognition remains subject to the relevant professional body's own requirements and assessment."],
  ["What engineering evidence can be developed?", "Evidence can include engineering baselines, maturity registers, integrated schedules, EVM dashboards, risk and change registers and readiness packs."],
  ["What does the IPC Bursary Route cover?", "For approved applicants who cannot access DfE funding, it can reduce the cost of selected pathways delivered through KBC."],
  ["Are places offered on a first-come, first-served basis?", "Yes. Funded and bursary places are limited and remain subject to suitability, eligibility, approval and written confirmation."],
];

export default function EngineeringManufacturingPage() {
  const [selectedCredits, setSelectedCredits] = useState<string[]>([]);
  const [routeChecks, setRouteChecks] = useState<Record<number, boolean>>({});
  const [openFaq, setOpenFaq] = useState<string | null>(null);
  const selectedCount = useMemo(() => 3 + selectedCredits.length, [selectedCredits]);

  const toggleCredit = (name: string) => {
    setSelectedCredits((current) => current.includes(name) ? current.filter((item) => item !== name) : current.length < 3 ? [...current, name] : current);
  };

  return (
    <div className="engineering-sector-page overflow-x-clip bg-white font-['Poppins',Arial,sans-serif] text-kbc-purple-950">
      <RouteMeta fallbackTitle="Engineering & Advanced Manufacturing Project Controls | Kent Business College" fallbackDescription="Professional project-controls pathways for engineering systems, advanced manufacturing, aerospace, automotive, rail and industrial automation." />

      <section className="relative overflow-hidden bg-kbc-purple-950 text-white">
        <div className="absolute inset-0 opacity-[.08] [background-image:linear-gradient(rgba(255,255,255,.3)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.3)_1px,transparent_1px)] [background-size:54px_54px]" />
        <div className={`${shell} relative grid min-h-[720px] grid-cols-[1.02fr_.98fr] items-center gap-20 py-20 max-[900px]:grid-cols-1`}>
          <div className="min-w-0">
            <Link className="mb-8 inline-flex items-center text-xs font-semibold text-white/65 hover:text-white" to="/sectors">← Back to all sectors</Link>
            <p className="text-[11px] font-bold uppercase tracking-[.16em] text-kbc-gold-500">Engineering & Advanced Manufacturing Sector</p>
            <h1 className="kbc-hero-title mt-5 max-w-[700px]">Control complex engineering programmes with <span className="text-kbc-gold-500">precision, integration and confidence.</span></h1>
            <p className="mt-7 max-w-[700px] text-[15px] leading-7 text-white/72">Professional project-controls pathways for people who connect engineering design, production, supply chains, quality, cost, schedule, risk, change and assurance across complex products, systems and assets.</p>
            <div className="mt-8 flex flex-wrap gap-3"><NavigationButton to="#pathways" variant="projectControls">Explore pathways</NavigationButton><NavigationButton to="#route-check" variant="projectControlsInverse">Check eligibility</NavigationButton></div>
            <div className="mt-7 flex flex-wrap gap-2">{["Operational Pathway", "Strategic Pathway", "Chartered Pathway", "PMO Certified"].map((item) => <span className="rounded-full border border-white/15 px-3 py-2 text-[10px] text-white/65" key={item}>{item}</span>)}</div>
          </div>
          <div className="min-w-0 rounded-[26px] border border-white/15 bg-white/[.06] p-7 shadow-2xl max-[520px]:p-5">
            <div className="flex items-start justify-between"><div><span className="text-[10px] uppercase tracking-[.15em] text-white/50">Engineering Delivery Control Room</span><h2 className="mt-2 font-['Source_Serif_4',Georgia,serif] text-3xl text-white">From design intent to production readiness.</h2></div><Factory className="text-kbc-gold-500" /></div>
            <div className="mt-7 grid grid-cols-2 gap-3 max-[520px]:grid-cols-1">{[["Design maturity", "Requirements, interfaces and approvals connected"], ["Schedule confidence", "Engineering, sourcing and production integrated"], ["Quality gates", "Verification and readiness evidence visible"], ["Change exposure", "Impact assessed before commitment"]].map(([label, value]) => <article className="min-w-0 rounded-xl border border-white/12 bg-white/[.06] p-5" key={label}><span className="text-[10px] text-kbc-gold-500">{label}</span><b className="mt-3 block text-sm text-white">{value}</b></article>)}</div>
            <div className="mt-4 rounded-xl bg-kbc-gold-500 p-5 text-kbc-purple-950"><b>Turn engineering information into reliable delivery decisions.</b><p className="mt-2 text-xs">Connect requirements, scope, schedule, cost, risk, quality, change and assurance.</p></div>
          </div>
        </div>
        <div className="relative border-t border-white/15"><div className={`${shell} grid grid-cols-5 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1`}>{[["Engineering-system focus", "Manufacturing, aerospace, automotive, rail and industrial systems."], ["Work-based evidence", "Apply learning to live products, assets, projects and programmes."], ["Flexible pathways", "Operational, Strategic, Chartered and PMO routes."], ["Two access routes", "DfE Funded Route or IPC Bursary Route."], ["Engineering application", "Requirements, readiness, interfaces and assurance."]].map(([title, body]) => <div className="border-r border-white/15 p-6" key={title}><b className="text-[10px] uppercase tracking-[.14em] text-kbc-gold-500">{title}</b><p className="mt-2 text-xs leading-5 text-white/60">{body}</p></div>)}</div></div>
      </section>

      <section className={section}><div className={`${shell} grid grid-cols-[1.05fr_.95fr] gap-16 max-[850px]:grid-cols-1`}><div><p className={eyebrow}>Project controls that protect engineering value</p><h2 className={heading}>Deliver engineered systems with precision, predictability and controlled change.</h2><p className="mt-6 text-sm leading-8 text-kbc-purple-700">Engineering programmes operate through tightly connected requirements, design maturity, suppliers, tooling, quality, testing, production readiness and operational acceptance. Integrated controls help teams expose pressure earlier and make better decisions before cost and delay become embedded.</p></div><article className="rounded-[24px] bg-kbc-purple-950 p-8 text-white"><h3 className="font-['Source_Serif_4',Georgia,serif] text-4xl leading-[1.02] text-white">Stable baselines. Better trade-offs. Production-ready outcomes.</h3><p className="mt-6 text-sm leading-7 text-white/65">Connect engineering scope, planning, cost, risk, quality, change and governance in one coherent control environment across products, projects and portfolios.</p></article></div><div className={`${shell} mt-10 grid grid-cols-4 gap-4 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1`}>{[["Design visibility", "Connect requirements, design maturity, interfaces, decisions and approvals."], ["Cost and value", "Build credible forecasts and understand technical trade-offs."], ["Integrated planning", "Align engineering, sourcing, tooling, testing, production and launch milestones."], ["Risk and quality", "Identify technical, supply-chain and readiness exposure before commitment."]].map(([title, body]) => <article className="rounded-2xl border border-kbc-purple-100 p-6" key={title}><Gauge className="text-kbc-purple-600" size={22}/><h3 className="mt-7 font-['Source_Serif_4',Georgia,serif] text-2xl">{title}</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">{body}</p></article>)}</div></section>

      <section className={`${section} bg-kbc-purple-50`}><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Built for engineering delivery</p><h2 className={heading}>One professional foundation across complex engineering environments.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-kbc-purple-700">The same project-controls discipline supports different products, assets, production systems and regulatory environments. Select a domain to see how the delivery focus changes.</p></div><div className="mt-9 flex flex-wrap gap-2">{["Manufacturing", "Aerospace & defence", "Automotive", "Rail & transport", "Industrial systems"].map((item, index) => <span className={`rounded-full border px-4 py-2 text-xs font-semibold ${index === 0 ? "border-kbc-purple-950 bg-kbc-purple-950 text-white" : "border-kbc-purple-100 bg-white"}`} key={item}>{item}</span>)}</div><article className="mt-5 grid grid-cols-[.85fr_1.15fr] overflow-hidden rounded-[24px] bg-white shadow-lg max-[760px]:grid-cols-1"><div className="bg-kbc-purple-950 p-8 text-white"><p className="text-[10px] uppercase tracking-[.14em] text-kbc-gold-500">Advanced manufacturing and Industry 4.0</p><h3 className="mt-6 font-['Source_Serif_4',Georgia,serif] text-4xl text-white">Production systems, automation, digital operations and scale-up.</h3><Factory className="mt-12 h-24 w-24 text-kbc-gold-500" strokeWidth={.8}/></div><div className="p-8"><p className={eyebrow}>Advanced manufacturing</p><p className="text-sm leading-7 text-kbc-purple-700">Integrate product introduction, industrialisation, equipment readiness, supply chains, production planning, quality and performance improvement across advanced-manufacturing programmes.</p><div className="mt-7 grid grid-cols-2 gap-3">{["Product and production baselines", "Tooling and equipment readiness", "Supplier and interface control", "Quality, change and launch governance"].map((item) => <div className="rounded-xl bg-kbc-purple-50 p-5 text-xs font-semibold" key={item}><Check className="mb-3 text-kbc-purple-600" size={16}/>{item}</div>)}</div></div></article></div></section>

      <section className={section} id="pathways"><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Built on a professional pathway</p><h2 className={heading}>Choose the route that matches your role and responsibility.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-kbc-purple-700">Every pathway develops professional decision-making through a structured credit model, live teaching, work-based engineering evidence and access to relevant professional progression.</p></div><div className="mt-12 grid grid-cols-4 gap-4 max-[900px]:grid-cols-2 max-[520px]:grid-cols-1">{pathways.map(([meta, name, body, items], index) => <article className={`flex min-h-[360px] flex-col rounded-2xl p-6 ${index===0 ? "bg-kbc-purple-950 text-white" : "border border-kbc-purple-100 bg-white"}`} key={name as string}><span className={`text-[10px] font-bold uppercase ${index===0 ? "text-kbc-gold-500" : "text-kbc-purple-600"}`}>{meta as string}</span><h3 className={`mt-7 font-['Source_Serif_4',Georgia,serif] text-2xl ${index===0 ? "text-white" : ""}`}>{name as string}</h3><p className={`mt-4 text-xs leading-5 ${index===0 ? "text-white/60" : "text-kbc-purple-700"}`}>{body as string}</p><ul className={`mt-auto border-t pt-5 text-xs leading-7 ${index===0 ? "border-white/15 text-white/70" : "border-kbc-purple-100"}`}>{(items as string[]).map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

      <section className={`${section} bg-[#f3f0e8]`}><div className={`${shell} grid grid-cols-[.75fr_1.25fr] gap-16 max-[850px]:grid-cols-1`}><div><p className={eyebrow}>Build your credit structure</p><h2 className={heading}>Shape the pathway around your engineering responsibilities.</h2><p className="mt-6 text-sm leading-7 text-kbc-purple-700">Select a route to see the mandatory core and specialist options. The on-page builder is illustrative; final selections are confirmed during suitability and prior-learning review.</p><div className="mt-7 rounded-xl bg-kbc-purple-950 p-5 text-white"><b className="text-3xl text-kbc-gold-500">{selectedCount}</b><span className="ml-2 text-sm">of 6 credits selected</span></div></div><div className="rounded-[24px] bg-white p-7 shadow-xl"><div className="mb-6 flex flex-wrap gap-2">{["Operational", "Strategic", "Chartered", "PMO Certified"].map((item, index) => <button className={`rounded-full px-4 py-2 text-xs font-semibold ${index===0 ? "bg-kbc-purple-950 text-white" : "border border-kbc-purple-100"}`} key={item} type="button">{item}</button>)}</div><div className="grid gap-3">{creditOptions.map(([name, kind, credits], index) => { const selectable=index>1; const selected=selectedCredits.includes(name); return <button aria-pressed={selectable ? selected : true} className={`flex items-center justify-between rounded-xl border p-4 text-left ${selected ? "border-kbc-purple-600 bg-kbc-purple-50" : "border-kbc-purple-100"}`} disabled={!selectable} key={name} onClick={() => selectable && toggleCredit(name)} type="button"><span><b className="block text-sm">{name}</b><small className="text-kbc-purple-600">{kind}</small></span><b className="text-xs text-kbc-purple-600">{selectable ? selected ? "Selected" : credits : credits}</b></button>;})}</div></div></div></section>

      <section className={section}><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Engineering project-controls evidence</p><h2 className={heading}>Create the outputs that strengthen engineering delivery and assurance.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-kbc-purple-700">Demonstrate professional capability through evidence that supports real technical, commercial and programme decisions across products, assets and engineering portfolios.</p></div><div className="mt-12 grid grid-cols-3 gap-4 max-[850px]:grid-cols-2 max-[520px]:grid-cols-1">{outputs.map(([name, body], index) => <article className="rounded-2xl border border-kbc-purple-100 bg-white p-6" key={name}><span className="text-xs font-bold text-kbc-purple-600">{String(index+1).padStart(2,"0")}</span><div className="mt-6 flex h-20 items-end gap-2 rounded-xl bg-kbc-purple-50 p-4">{[42,65,51,80,68].map((height,i) => <i className={`${i===4 ? "bg-kbc-gold-500" : "bg-kbc-purple-600"} flex-1 rounded-t`} key={i} style={{height:`${height}%`}} />)}</div><h3 className="mt-6 font-['Source_Serif_4',Georgia,serif] text-2xl">{name}</h3><p className="mt-3 text-xs leading-5 text-kbc-purple-700">{body}</p></article>)}</div></div></section>

      <section className={`${section} bg-kbc-purple-950 text-white`}><div className={shell}><div className="max-w-[900px]"><p className="mb-4 text-[11px] font-bold uppercase tracking-[.16em] text-kbc-gold-500">Support engineering-delivery roles</p><h2 className={`${heading} !text-white`}>Prepare for roles that influence complex products, systems and programmes.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-white/65">Use project-controls capability to strengthen decision-making from concept and design through industrialisation, production, validation, launch and operational handover.</p></div><div className="mt-12 grid grid-cols-3 gap-4 max-[800px]:grid-cols-2 max-[520px]:grid-cols-1">{roles.map(([number, name, body]) => <article className="rounded-2xl border border-white/15 bg-white/[.05] p-6" key={number}><span className="text-xs font-bold text-kbc-gold-500">{number}</span><h3 className="mt-7 font-['Source_Serif_4',Georgia,serif] text-2xl text-white">{name}</h3><p className="mt-3 text-xs leading-5 text-white/60">{body}</p></article>)}</div></div></section>

      <section className={`${section} bg-[#f3f0e8]`}><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Applied professional learning</p><h2 className={heading}>From live teaching to engineering evidence.</h2></div><div className="mt-12 grid grid-cols-[.9fr_1.1fr] overflow-hidden rounded-[24px] bg-white shadow-lg max-[800px]:grid-cols-1"><img className="h-full min-h-[430px] w-full object-cover" src="/assets/images/programme-project-controls.jpg" alt="Applied engineering project-controls learning"/><div className="p-8"><p className={eyebrow}>Learn, apply, test and evidence</p><h3 className="font-['Source_Serif_4',Georgia,serif] text-4xl leading-[1.02]">Professional development connected to live engineering work.</h3><p className="mt-5 text-sm leading-7 text-kbc-purple-700">Build capability through structured learning, guided workplace application, coaching and evidence that reflects your actual role.</p><div className="mt-7 grid gap-3">{[["01","Live professional teaching","Concepts, methods, worked examples and sector discussion."], ["02","Workplace application","Use the methods on relevant engineering projects, products, programmes or portfolios."], ["03","Evidence and reflection","Demonstrate decisions, outputs, impact and professional learning."], ["04","Coaching and progress review","Maintain momentum, address gaps and prepare for assessment."]].map(([n,title,body]) => <div className="grid grid-cols-[42px_1fr] gap-3 rounded-xl bg-kbc-purple-50 p-4" key={n}><b className="text-kbc-purple-600">{n}</b><div><b className="text-sm">{title}</b><p className="mt-1 text-xs text-kbc-purple-700">{body}</p></div></div>)}</div></div></div></div></section>

      <section className={section}><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Professional insight</p><h2 className={heading}>Learn from recognised project, portfolio and PMO expertise.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-kbc-purple-700">Expert involvement should be confirmed for each cohort and module. These profiles represent KBC's wider professional community and expertise relevant to planning, portfolios, PMO and complex engineering delivery.</p></div><div className="mt-12 grid grid-cols-3 gap-5 max-[760px]:grid-cols-1">{[["Steve Wake","Planning & controls","Project-controls practice, planning, scheduling and professional capability."], ["Stephen Jenner","Portfolio & benefits","Portfolio management, benefits realisation and strategic governance."], ["Ray Mead","PMO & P3M capability","PMO operating models, organisational capability and programme governance."]].map(([name,focus,body],index) => <article className="overflow-hidden rounded-2xl border border-kbc-purple-100 bg-white" key={name}>{index===0&&<img className="h-52 w-full object-cover" src="/assets/images/figma-home/project-speaker.png" alt="Steve Wake speaking about project controls"/>}<div className="p-6"><span className="text-[10px] font-bold uppercase text-kbc-purple-600">{focus}</span><h3 className="mt-5 font-['Source_Serif_4',Georgia,serif] text-3xl">{name}</h3><p className="mt-4 text-xs leading-6 text-kbc-purple-700">{body}</p></div></article>)}</div></div></section>

      <section className={`${section} bg-kbc-purple-50`}><div className={shell}><div className="max-w-[900px]"><p className={eyebrow}>Funding and bursary access</p><h2 className={heading}>One professional pathway. Two access routes.</h2><p className="mt-6 max-w-[760px] text-sm leading-7 text-kbc-purple-700">Choose the professional pathway that reflects your responsibilities. KBC can then assess whether the Department for Education Funded Route or the IPC Bursary Route is more appropriate.</p></div><div className="mt-12 grid grid-cols-2 gap-5 max-[760px]:grid-cols-1"><article className="rounded-[24px] bg-white p-8 shadow-lg"><span className="text-[10px] font-bold uppercase text-kbc-purple-600">Department for Education</span><h3 className="mt-6 font-['Source_Serif_4',Georgia,serif] text-4xl">DfE Funded Route</h3><p className="mt-4 text-sm leading-7 text-kbc-purple-700">Eligible employees may be able to access a six-credit pathway on a fully funded basis, subject to the applicable rules and written confirmation.</p><ul className="mt-6 space-y-3">{["Paid employment in England","Employer participation and approval","Relevant workplace activity","Paid learning time agreed","Residency, prior-learning and funding assessment"].map((item) => <li className="flex gap-3 text-sm" key={item}><Check className="text-kbc-purple-600" size={17}/>{item}</li>)}</ul><NavigationButton className="mt-7" to="#route-check">Check funded-route eligibility</NavigationButton></article><article className="rounded-[24px] bg-kbc-purple-950 p-8 text-white shadow-lg"><span className="text-[10px] font-bold uppercase text-kbc-gold-500">Institute of Project Controls</span><h3 className="mt-6 font-['Source_Serif_4',Georgia,serif] text-4xl text-white">IPC Bursary Route</h3><p className="mt-4 text-sm leading-7 text-white/65">For suitable applicants who cannot access the Funded Route, IPC bursary support can reduce the cost of selected pathways delivered through KBC.</p><ul className="mt-6 space-y-3 text-sm text-white/75">{["50% bursary · Operational Pathway","50% bursary · Strategic Pathway","75% bursary · Chartered Pathway","Flexible instalments up to 36 months","Subject to approval, suitability and availability"].map((item) => <li className="flex gap-3" key={item}><Check className="text-kbc-gold-500" size={17}/>{item}</li>)}</ul><NavigationButton className="mt-7" to="/contact" variant="projectControls">Apply for IPC bursary support</NavigationButton></article></div><p className="mt-6 rounded-xl bg-kbc-gold-50 p-5 text-xs leading-6 text-kbc-purple-700"><b>Limited places:</b> Funded and IPC bursary places are limited and offered on a first-come, first-served basis, subject to eligibility, pathway suitability, employer participation where required and written confirmation.</p></div></section>

      <section className={section} id="route-check"><div className={`${shell} grid grid-cols-[.72fr_1.28fr] gap-16 max-[800px]:grid-cols-1`}><div><p className={eyebrow}>Initial route check</p><h2 className={heading}>Which access route may suit your circumstances?</h2><p className="mt-6 text-sm leading-7 text-kbc-purple-700">Complete this short, non-binding check. It provides an initial direction only; KBC must still complete formal eligibility, prior-learning, employer and pathway suitability reviews.</p><div className="mt-7 rounded-2xl bg-kbc-purple-950 p-6 text-white"><Sparkles className="text-kbc-gold-500"/><h3 className="mt-5 font-['Source_Serif_4',Georgia,serif] text-2xl text-white">{Object.values(routeChecks).filter(Boolean).length >= 4 ? "The DfE Funded Route may be a suitable starting point." : "Start by selecting the statements that apply."}</h3><p className="mt-3 text-xs text-white/60">Your answers indicate which route may be the better starting point. Formal assessment still applies.</p></div></div><div className="grid gap-3">{[["I am in paid employment in England.","The Funded Route normally requires eligible employment in England."], ["My employer is willing to support the pathway.","Employer approval and participation are required for the DfE route."], ["My role includes relevant engineering, project, programme, PMO or controls activity.","Workplace responsibilities should support learning and evidence."], ["My employer can provide the required paid learning time.","The exact commitment is agreed in the training plan."], ["I meet the residency and current funding requirements.","Formal checks are completed before enrolment."]].map(([statement,note],index) => <button aria-pressed={routeChecks[index] || false} className={`flex items-start gap-4 rounded-xl border p-5 text-left ${routeChecks[index] ? "border-kbc-purple-600 bg-kbc-purple-50" : "border-kbc-purple-100"}`} key={statement} onClick={() => setRouteChecks((current) => ({...current,[index]:!current[index]}))} type="button"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded border ${routeChecks[index] ? "border-kbc-purple-600 bg-kbc-purple-600 text-white" : "border-kbc-purple-200"}`}>{routeChecks[index] && <Check size={12}/>}</span><span><b className="block text-sm">{statement}</b><small className="mt-1 block text-kbc-purple-700">{note}</small></span></button>)}</div></div></section>

      <section className={`${section} bg-[#f3f0e8]`}><div className={`${shell} grid grid-cols-[.65fr_1.35fr] gap-16 max-[800px]:grid-cols-1`}><div><p className={eyebrow}>Questions before you enquire</p><h2 className={heading}>Frequently asked questions.</h2><p className="mt-6 text-sm leading-7 text-kbc-purple-700">Funding, pathway and professional-recognition outcomes remain subject to formal assessment and written confirmation.</p></div><div className="grid gap-3">{faqs.map(([question,answer]) => <article className="rounded-xl border border-kbc-purple-100 bg-white" key={question}><button aria-expanded={openFaq===question} className="flex w-full items-center justify-between gap-5 p-5 text-left text-sm font-semibold" onClick={() => setOpenFaq(openFaq===question?null:question)} type="button">{question}<ChevronDown className={`shrink-0 transition ${openFaq===question?"rotate-180":""}`} size={18}/></button>{openFaq===question&&<p className="border-t border-kbc-purple-100 px-5 py-5 text-xs leading-6 text-kbc-purple-700">{answer}</p>}</article>)}</div></div></section>

      <section className="bg-kbc-purple-950 py-24 text-center text-white"><div className={`${shell} flex flex-col items-center`}><p className="text-[11px] font-bold uppercase tracking-[.16em] text-kbc-gold-500">Ready to take control</p><h2 className="mt-5 max-w-[850px] font-['Source_Serif_4',Georgia,serif] text-[clamp(44px,5vw,68px)] font-semibold leading-[1.01] tracking-[-.045em] text-white">Build the capability to deliver complex engineering programmes with confidence.</h2><p className="mt-6 max-w-[720px] text-sm leading-7 text-white/65">Compare the pathways, complete an initial eligibility check or book a conversation about your organisation's engineering project-controls needs.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><NavigationButton to="#route-check" variant="projectControls">Check eligibility <ArrowRight size={17}/></NavigationButton><NavigationButton to="#pathways" variant="projectControlsInverse">Compare pathways</NavigationButton></div></div></section>
    </div>
  );
}
