export const endpoints = {
  site: "/site/",
  navigation: "/navigation/",
  page: (slug: string) => `/pages/${encodeURIComponent(slug)}/`,
  colleges: (query = "") => `/colleges/${query}`,
  college: (slug: string) => `/colleges/${encodeURIComponent(slug)}/`,
  programmes: (query = "") => `/programmes/${query}`,
  programme: (slug: string) => `/programmes/${encodeURIComponent(slug)}/`,
  events: (query = "") => `/events/${query}`,
  event: (slug: string) => `/events/${encodeURIComponent(slug)}/`,
  people: (query = "") => `/people/${query}`,
  stories: (query = "") => `/stories/${query}`,
  story: (slug: string) => `/stories/${encodeURIComponent(slug)}/`,
  articles: (query = "") => `/articles/${query}`,
  article: (slug: string) => `/articles/${encodeURIComponent(slug)}/`,
  search: (query: string) => `/search/?q=${encodeURIComponent(query)}`,
  contact: "/forms/contact/",
  support: "/forms/support/",
  eligibility: "/forms/eligibility/",
  employerAgreement: "/forms/employer-agreement/",
  newsletter: "/newsletter/subscribe/",
} as const;
