# Generated by Django 5.2.16 on 2026-08-04 12:53

import apps.forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.forms.models.new_reference, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('interest', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EligibilitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.forms.models.new_reference, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerAgreementSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.forms.models.new_reference, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('organisation', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=apps.forms.models.new_reference, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField()),
                ('delivery_status', models.CharField(choices=[('received', 'Received'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
