# Generated by Django 5.2.16 on 2026-08-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitysubmission',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.programme'),
        ),
    ]
