# Generated by Django 5.2.16 on 2026-08-04 12:53

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('awarding_body', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeEligibilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('level', models.PositiveSmallIntegerField(db_index=True)),
                ('funding_type', models.CharField(choices=[('fully-funded', 'Fully funded'), ('co-funded', 'Co-funded'), ('commercial', 'Commercial')], db_index=True, max_length=20)),
                ('funding_label', models.CharField(max_length=100)),
                ('duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_label', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In person'), ('blended', 'Blended')], max_length=20)),
                ('delivery_schedule', models.CharField(blank=True, max_length=250)),
                ('cta_label', models.CharField(default='Enquire now', max_length=80)),
                ('cta_url', models.CharField(default='/eligibility', max_length=300)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('legacy_source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='colleges.college')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
