# Generated by Django 5.2.16 on 2026-08-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='programme',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programmecertification',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='programmeeligibilityitem',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_items', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='programmemodule',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='programmes.programme'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['status', 'college', 'level'], name='programmes__status_69268a_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['status', 'funding_type', 'is_featured'], name='programmes__status_1e5cd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='programme_level_positive'),
        ),
        migrations.AddConstraint(
            model_name='programmemodule',
            constraint=models.UniqueConstraint(fields=('programme', 'sort_order'), name='unique_programme_module_order'),
        ),
    ]
