// Content contracts only; published values are supplied by Django.
export type HomeContent = {
  metadata: { "title": string; "description": string };
  hero: { "copy": { "poster": string; "src": string; "src2": string; "paragraph": string; "heading": string; "text": string; "paragraph2": string; "to": string; "linkLabel": string; "to2": string; "linkLabel2": string; "text2": string; "text3": string; "text4": string; "text5": string; "text6": string; "text7": string; "text8": string; "text9": string; "src3": string; "alt": string; "text10": string; "text11": string } };
  trusted: { "trustedOrganisationLogos": ({ "name": string; "image": string })[]; "copy": { "eyebrow": string; "title": string; "description": string; "to": string; "linkLabel": string } };
  development: { "audienceContent": { "professionals": { "cards": ({ "eyebrow": string; "title": string; "description": string; "points": (string)[]; "note"?: string })[]; "image": string; "imageAlt": string; "stats": ({ "value": string; "label": string })[]; "primaryLabel": string; "primaryTo": string; "secondaryLabel": string; "secondaryTo": string }; "employers": { "cards": ({ "eyebrow": string; "title": string; "description": string; "linkLabel": string; "to": string; "emphasis"?: string; "emphasisGold"?: boolean; "detail"?: string })[]; "image": string; "imageAlt": string; "stats": ({ "value": string; "label": string })[]; "primaryLabel": string; "primaryTo": string; "secondaryLabel": string; "secondaryTo": string } }; "copy": { "eyebrow": string; "title": string; "description": string; "note": string; "text": string; "text2": string; "note2": string; "text3": string; "text4": string; "paragraph": string } };
  colleges: { "colleges": ({ "number": string; "category": string; "title": string; "tags": (string)[]; "cta": string; "href": string; "tone": "navy" | "teal" | "coral" | "plum" })[]; "copy": { "eyebrow": string; "title": string; "description": string } };
  programmes: { "programmes": ({ "number": string; "level": string; "category": string; "title": string; "description": string; "href": string; "tone": "controls" | "management" | "marketing" })[]; "copy": { "eyebrow": string; "title": string; "text": string; "to": string; "linkLabel": string } };
  applied: { "journeySteps": ({ "number": string; "title": string; "description": string })[]; "copy": { "eyebrow": string; "title": string; "description": string } };
  experience: { "qualifications": (string)[]; "fundBenefits": (string)[]; "supportBenefits": (string)[]; "eventBenefits": (string)[]; "workshopLocations": (string)[]; "copy": { "eyebrow": string; "title": string; "description": string; "text": string; "src": string; "alt": string; "text2": string; "heading": string; "to": string; "linkLabel": string; "text3": string; "heading2": string; "paragraph": string; "src2": string; "alt2": string; "text4": string; "heading3": string; "paragraph2": string; "note": string; "to2": string; "linkLabel2": string; "src3": string; "alt3": string; "text5": string; "heading4": string; "text6": string; "text7": string; "text8": string; "heading5": string; "src4": string; "alt4": string; "text9": string; "text10": string; "text11": string; "heading6": string; "text12": string; "text13": string; "text14": string; "text15": string; "heading7": string; "src5": string; "alt5": string; "text16": string; "text17": string; "text18": string; "text19": string; "src6": string; "alt6": string; "text20": string; "text21": string; "text22": string; "text23": string; "paragraph3": string; "note2": string; "to3": string; "linkLabel3": string } };
  support: { "supportItems": ({ "title": string; "description": string; "note"?: string; "icon": "UserRoundCheck" | "CalendarCheck2" | "HeartHandshake" | "ClipboardCheck" | "UsersRound" | "ChartNoAxesColumnIncreasing" })[]; "journey": (string)[]; "copy": { "eyebrow": string; "title": string; "description": string } };
  events: { "eyebrow": string; "title": string; "description": string; "featuredActionLabel": string; "viewAllLabel": string; "fallbackImages": (string)[] };
  careers: { "careerPaths": ({ "id": string; "tab": string; "role": string; "roleDescription": string; "capability": string; "capabilityDescription": string; "programmes": ({ "title": string; "level": string; "href": string })[] })[]; "copy": { "eyebrow": string; "title": string; "description": string; "text": string; "text2": string; "text3": string; "to": string; "linkLabel": string } };
  progression: { "pathwaySteps": ({ "number": string; "title": string; "description": string; "tone": "quiet" | "primary" | "outlined" })[]; "copy": { "eyebrow": string; "title": string; "description": string; "text": string; "to": string; "paragraph": string; "paragraph2": string; "paragraph3": string } };
  recognition: { "recognitionLogos": ({ "name": string; "src": string })[]; "copy": { "eyebrow": string; "title": string; "description": string; "paragraph": string } };
  testimonials: { "items": ({ "name": string; "role": string; "image": string; "quote": string })[]; "eyebrow": string; "backgroundImage": string };
  funding: { "copy": { "paragraph": string; "heading": string; "heading2": string; "paragraph2": string; "note": string; "to": string; "linkLabel": string; "to2": string; "linkLabel2": string; "to3": string; "linkLabel3": string } };
};
export type HomeSection = keyof HomeContent;
