export type PathwaySlug = "operational" | "strategic" | "chartered";

export interface PathwayModule { number: string; title: string; summary: string; details: string[]; output: string; meta: string; }
export interface PathwayData {
  slug: PathwaySlug; eyebrow: string; title: string; lead: string; promise: string;
  heroBuild: string[];
  stats: { value: string; label: string }[]; overview: { title: string; text: string }[];
  overviewTitle: string; overviewLead: string; importantDistinction: string;
  modulesTitle: string; modulesIntro: string; modules: PathwayModule[]; roles: string[];
  roleProvides: string[]; assessmentChecks: string[]; certificationEligibility: string;
  capabilities: string[]; evidence: string[]; recognitionTitle: string; recognition: string; reviewed: string;
}

export const pathwayData: Record<PathwaySlug, PathwayData> = {
  operational: {
    slug: "operational", eyebrow: "2026/27 learner and employer pathway", title: "Operational Pathway",
    lead: "Build integrated planning, cost, risk and performance capability for complex projects, with evidence-led decision support at the centre.", promise: "Control. Assure. Act.",
    heroBuild: ["Integrated planning, cost, risk and performance control.", "Operational project leadership and decision support.", "Data assurance, forecasting and recovery recommendations.", "Credible workplace evidence mapped to the apprenticeship.", "Preparation for selected external professional examinations."],
    stats: [{ value: "6", label: "Pathway credits" }, { value: "835", label: "Minimum training hours" }, { value: "£27k", label: "Maximum funding band" }],
    overviewTitle: "An operational route built around control, assurance and action.", overviewLead: "The Operational Pathway develops professionals who do more than report project status. They establish credible controls, challenge data, model outcomes and provide evidence-based recommendations that influence delivery.", importantDistinction: "The apprenticeship, KBC pathway modules and external certifications are separate outcomes. The apprenticeship is awarded after successful end-point assessment. PMI, APM and APMG qualifications are awarded only by the relevant professional body after its own eligibility, registration and examination requirements are met.",
    overview: [
      { title: "Integrated control", text: "Connect scope, schedule, cost, risk, change and performance into one credible control system." },
      { title: "Data assurance", text: "Improve data quality, forecasting, early warning and recovery recommendations." },
      { title: "Professional preparation", text: "Apply learning at work, build authentic evidence and prepare for relevant independent examinations." },
    ],
    modulesTitle: "Select six pathway credits", modulesIntro: "The final mix is agreed around the learner’s role, prior learning and employer priorities. The written offer confirms the controlled module and examination package.",
    modules: [
      { number: "01–02", title: "PMP Exam Preparation", summary: "Strengthen delivery, governance, stakeholder and decision-making practice across predictive, agile and hybrid environments.", details: ["People and stakeholder leadership", "Delivery governance and value", "Risk, change and recovery"], output: "Applied project charter, governance map and delivery recommendation.", meta: "2 credits · indicative 8 months" },
      { number: "03", title: "AI in Project Controls", summary: "Use governed AI workflows and automation to support reliable controls information without removing human accountability.", details: ["Structured prompting", "Governed data models", "Dashboards and workflow automation"], output: "Governed workflow, dashboard or bounded decision-support tool.", meta: "1 credit · indicative 4 months" },
      { number: "04–05", title: "Project Planning and Control", summary: "Build credible integrated baselines and translate project performance into clear management action.", details: ["Planning and scheduling", "Cost and earned value", "Risk, assurance and reporting"], output: "Integrated baseline, performance report and forecast narrative.", meta: "2 credits · indicative 8 months" },
      { number: "06", title: "Specialist elective", summary: "Choose development that best matches workplace responsibility and evidence opportunity.", details: ["Project risk management", "Earned Value Management", "Professional scheduling"], output: "A role-relevant specialist artefact and reflective evidence.", meta: "1 credit · indicative 4 months" },
    ],
    roles: ["Project Controls professionals", "Planning and scheduling specialists", "Cost and earned-value analysts", "Risk and assurance specialists", "PMO and performance professionals", "Professionals moving into controls leadership"],
    roleProvides: ["Responsibility for controls information, methods or recommendations.", "Access to schedules, cost, risk, progress, change or reporting data.", "Opportunities to influence project, programme or portfolio stakeholders.", "A line manager who can support application and authenticate evidence.", "Sufficient new learning after recognition of prior experience."],
    assessmentChecks: ["Learner and residency eligibility.", "Employment and working location.", "Role alignment to ST0845 duties.", "Prior learning, qualifications and experience.", "English, maths and learning support.", "Ability to complete within available employment time."],
    certificationEligibility: "Experienced apprentices may still need to satisfy professional-body experience, education, application, audit and examination requirements. KBC preparation does not override those rules.",
    capabilities: ["Integrated baselines", "Planning and scheduling", "Cost engineering", "Risk and opportunity", "Progress and performance", "Data assurance", "Change and recovery", "Commercial awareness", "Leadership and ethics"],
    evidence: ["Controls strategy", "Integrated baseline", "Schedule assurance review", "Cost and EVM analysis", "Risk and change evidence", "AI or automation workflow", "Decision-support briefing", "Leadership reflection"],
    recognitionTitle: "Apprenticeship and certification are separate", recognition: "The pathway develops the full ST0845 occupational capability. Any professional qualification or external examination is independently awarded and is included only where it is confirmed in the learner’s written offer.", reviewed: "Information reviewed 25 July 2026.",
  },
  strategic: {
    slug: "strategic", eyebrow: "2026/27 learner and employer pathway", title: "Strategic Pathway", lead: "Progress from project leadership to programme, portfolio and PMO decision-making through six connected pathway credits.", promise: "From evidence to action.",
    heroBuild: ["Strategic project leadership and governance.", "Programme-level coordination and benefits oversight.", "Portfolio prioritisation and investment confidence.", "PMO leadership and measurable service value.", "Governed AI for stronger decision support."],
    stats: [{ value: "6", label: "Pathway credits" }, { value: "48m", label: "Published typical duration" }, { value: "£27k", label: "Maximum funding band" }],
    overviewTitle: "A strategic route from project leadership to enterprise decision-making.", overviewLead: "The Strategic Pathway develops professionals who can connect project evidence to programme, portfolio and PMO decisions. It builds the judgement needed to turn complexity into clear recommendations and practical value.", importantDistinction: "KBC pathway credits organise the professional-development journey and are not regulated higher-education credits. External awards remain separate and are subject to the current requirements of their awarding bodies.",
    overview: [{ title: "Reliable evidence", text: "Create an assured view of delivery, risk, resources, benefits and performance." }, { title: "Clear recommendations", text: "Translate complex evidence into choices, trade-offs and decision-ready advice." }, { title: "Practical value", text: "Apply strategic tools to current workplace challenges and demonstrate measurable improvement." }],
    modulesTitle: "Your six-credit journey", modulesIntro: "The sequence moves from strategic project leadership into governed AI, programme, portfolio and PMO leadership. A credit is a KBC pathway unit, not a regulated higher-education credit.",
    modules: [
      { number: "01–02", title: "PMP & Strategic Project Leadership", summary: "Connect governance, people, delivery and benefits to organisational priorities.", details: ["Stakeholder and people leadership", "Governance and decision rights", "Value, recovery and benefits"], output: "Strategic charter, governance map, recovery recommendation and benefits narrative.", meta: "2 pathway credits" },
      { number: "03", title: "AI in Project Controls", summary: "Design governed AI and automation that improve decision support while retaining approval and audit controls.", details: ["Prompt and data design", "n8n automation", "Dashboards and bounded agents"], output: "Governed workflow, dashboard or agent with assurance controls.", meta: "1 pathway credit" },
      { number: "04", title: "Programme Management", summary: "Lead coordinated change through vision, governance, benefits, tranches and dependencies.", details: ["Purpose and sponsorship", "Benefits and dependencies", "Assurance and roadmap"], output: "Governance map, benefits strategy, programme roadmap and dashboard.", meta: "1 pathway credit" },
      { number: "05", title: "Portfolio Management", summary: "Align investment to strategy and balance priority, risk, benefits, capacity and change demand.", details: ["Strategic alignment", "Prioritisation and balance", "Capacity and benefits"], output: "Prioritisation model, investment pack, heatmap and portfolio dashboard.", meta: "1 pathway credit" },
      { number: "06", title: "PMO Leadership", summary: "Shape a PMO around customers, services, measurable value and an achievable maturity roadmap.", details: ["Mandate and operating model", "Services and customers", "Value, maturity and leadership"], output: "PMO value proposition, service catalogue, roadmap and scorecard.", meta: "1 pathway credit" },
    ],
    roles: ["Senior project controls professionals", "Programme and portfolio professionals", "PMO managers and leads", "Transformation and governance specialists", "Delivery assurance leaders", "Professionals advising senior decision-makers"],
    roleProvides: ["Responsibility for strategic delivery information and recommendations.", "Access to programme, portfolio, benefits and governance evidence.", "Opportunities to influence sponsors and senior decision-makers.", "Authority to test or improve operating models and controls.", "Sufficient new learning after recognition of prior experience."],
    assessmentChecks: ["Learner and residency eligibility.", "Employment and working location.", "Role alignment to ST0845 duties.", "Prior learning, qualifications and experience.", "English, maths and learning support.", "Access to suitable strategic evidence."],
    certificationEligibility: "Professional certifications and examinations remain separately awarded. Eligibility, prerequisites, application and examination rules are set by the relevant professional body.",
    capabilities: ["Strategic alignment", "Project leadership", "Programme governance", "Portfolio prioritisation", "Benefits oversight", "PMO operating models", "Decision support", "Responsible AI", "Executive influence"],
    evidence: ["Strategic charter", "Stakeholder and governance map", "Recovery recommendation", "Governed AI workflow", "Programme roadmap", "Portfolio investment pack", "PMO service catalogue", "Executive scorecard"],
    recognitionTitle: "Professional preparation with clear boundaries", recognition: "Professional components support development and examination preparation. External awards remain subject to the current rules of the relevant awarding body and the exact package confirmed in writing.", reviewed: "Information reviewed 25 July 2026.",
  },
  chartered: {
    slug: "chartered", eyebrow: "2026/27 chartered pathway", title: "Chartered Pathway", lead: "Develop strategic PMO, integrated controls, stakeholder, risk, portfolio and earned-value capability—with an APM-recognised technical-knowledge route supporting eligible professionals towards ChPP.", promise: "Technical knowledge. Professional practice. Chartered ambition.",
    heroBuild: ["Advanced technical knowledge and integrated controls.", "Professional practice, judgement and workplace impact.", "Governance, assurance and strategic PMO capability.", "Ethics, reflection and continuing professional development.", "A stronger evidence base for a later ChPP application."],
    stats: [{ value: "4", label: "Certified PMO modules" }, { value: "3", label: "Specialist components" }, { value: "£27k", label: "Maximum funding band" }],
    overviewTitle: "A pathway built around credible professional evidence.", overviewLead: "The Chartered Pathway combines the complete Project Controls Professional Level 6 apprenticeship with Certified PMO, applied AI, portfolio management and earned-value development for professionals pursuing stronger workplace impact and future chartered recognition.", importantDistinction: "Completing the pathway does not itself award Chartered Project Professional status. ChPP is awarded only by APM after the candidate meets its eligibility, professional-practice, CPD, ethics, written-submission and interview requirements.",
    overview: [{ title: "Technical knowledge", text: "Build advanced understanding of governance, integrated controls, risk, quality, stakeholder leadership and assurance." }, { title: "Professional practice", text: "Apply learning in authentic environments and organise credible evidence of judgement, autonomy and impact." }, { title: "Ethics and CPD", text: "Develop reflective practice, professional conduct and an evidence-led improvement mindset." }, { title: "Chartered readiness", text: "Understand APM Pathway 2 expectations and prepare a stronger evidence base for a later independent application." }],
    modulesTitle: "Seven internal pathway components", modulesIntro: "The route combines the four-module Certified PMO Professional Level 6 programme with three specialist components. Every apprentice still completes the full ST0845 occupational standard.",
    modules: [
      { number: "01", title: "PMO Governance", summary: "Establish the strategic purpose, authority, operating model and assurance arrangements of an effective PMO.", details: ["PMO models and governance", "Decision rights and stage gates", "Benefits, ethics and culture"], output: "Operating model, RACI, decision log and assurance review.", meta: "Certified PMO · indicative 4 months" },
      { number: "02", title: "Integrated Controls", summary: "Translate scope into controlled baselines and maintain confidence through performance and forecast evidence.", details: ["Scope, schedule and cost", "Critical path and resources", "EVM, forecasting and change"], output: "WBS, baseline schedule, EVM report, forecast and change log.", meta: "Certified PMO · indicative 4 months" },
      { number: "03", title: "Risk, Issue and Quality", summary: "Replace reactive firefighting with integrated uncertainty management, assurance and learning.", details: ["Risk analysis and ownership", "Quality assurance and acceptance", "Root cause and continuous improvement"], output: "Risk response, quality plan, assurance evidence and lessons log.", meta: "Certified PMO · indicative 4 months" },
      { number: "04", title: "Stakeholders and Reporting", summary: "Use stakeholder insight, communication and evidence-based reporting to influence decisions and realise value.", details: ["Stakeholder analysis", "Executive reporting", "Influence and negotiation"], output: "Engagement plan, exception report, dashboard and engagement metrics.", meta: "Certified PMO · indicative 4 months" },
      { number: "05", title: "AI in Project Controls", summary: "Build governed AI workflows, dashboards and decision-support tools while protecting accountability.", details: ["Structured prompting", "Data and workflow governance", "Human approval and audit trail"], output: "Prompt library, workflow, dashboard, AI policy and applied capstone.", meta: "KBC specialist development" },
      { number: "06", title: "Portfolio Management", summary: "Align investment with strategy and balance priorities, resources, benefits and portfolio-level risk.", details: ["Strategic alignment", "Prioritisation and balance", "Portfolio governance"], output: "Prioritisation model, portfolio dashboard and benefits map.", meta: "Independent professional development" },
      { number: "07", title: "Earned Value Management", summary: "Measure health objectively, forecast likely outcomes and turn integrated evidence into timely action.", details: ["Performance baseline", "CPI, SPI and EAC", "Variance and corrective action"], output: "EVM implementation plan, performance report and recovery recommendation.", meta: "APMG certification context" },
    ],
    roles: ["Project Controls Managers", "Heads of Planning and Scheduling", "Cost Engineering Leads", "PMO Managers and Leads", "Risk and controls-assurance specialists", "Programme and portfolio controls professionals"],
    roleProvides: ["Responsibility for governance, controls or assurance recommendations.", "Access to integrated schedule, cost, risk and portfolio information.", "Opportunities to influence senior stakeholders and decision forums.", "Scope to lead PMO or controls improvement.", "Authentic evidence of professional judgement and impact."],
    assessmentChecks: ["Learner and residency eligibility.", "Employment and working location.", "Role alignment to ST0845 duties.", "Prior learning, qualifications and experience.", "English, maths and learning support.", "Access to evidence suitable for professional reflection."],
    certificationEligibility: "APM separately determines eligibility for ChPP. A recognised technical-knowledge route does not replace the professional-practice submission, current CPD, ethics commitment or professional interview.",
    capabilities: ["Strategy and governance", "Scope and integrated baselines", "Estimating and cost engineering", "Planning and scheduling", "Performance and forecasting", "Risk, quality and safety", "Commercial and supply chain", "Data and digital controls", "Leadership and professional conduct"],
    evidence: ["PMO operating model", "Integrated baseline", "Risk and quality framework", "Portfolio dashboard", "EVM report", "Governed AI workflow", "Assurance review", "Executive briefing", "Professional reflection"],
    recognitionTitle: "ChPP is a separate professional award", recognition: "Completing this pathway does not award Chartered Project Professional status. Certified PMO can provide recognised technical-knowledge evidence for an eligible APM Pathway 2 application; APM separately assesses eligibility, professional practice, CPD, ethics, written evidence and interview.", reviewed: "Information reviewed 25 July 2026.",
  },
};

export const eligibility = ["UK resident for the past three years, subject to the applicable funding rules.", "Has the right to work and does not require unsupported sponsorship arrangements.", "Not enrolled in another government-funded training programme at the same time.", "In paid employment in England in a productive, relevant role.", "Employer is based in England and uses the Apprenticeship Service.", "Normally works at least 16 hours a week and spends at least 50% of working time in England."];
export const funding = [{ title: "Levy employer", text: "Eligible costs may be paid from available apprenticeship levy funds." }, { title: "Age 16–24", text: "Some eligible non-levy learners may receive 100% government funding under the applicable 2026/27 rules." }, { title: "Levy shortfall", text: "The published scenario indicates 75% government contribution and 25% employer contribution where applicable." }, { title: "Age 25+ non-levy", text: "The published scenario indicates 95% government contribution and 5% employer contribution where applicable." }];
