# Generated by Django 5.2.16 on 2026-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.CharField(db_index=True, max_length=50)),
                ('operation', models.CharField(max_length=100)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'status', 'created_at'], name='integration_integra_ab1b69_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(default='legacy-wordpress', max_length=50)),
                ('source_type', models.CharField(db_index=True, max_length=80)),
                ('source_id', models.CharField(db_index=True, max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=120)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('dry_run', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_type', 'source_id', 'checksum', 'dry_run'), name='unique_migration_log_attempt')],
            },
        ),
    ]
