# Generated by Django 5.2.16 on 2026-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='media/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], max_length=16)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('caption', models.TextField(blank=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy_source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='media_libra_kind_a69ade_idx')],
            },
        ),
    ]
