# Generated by Django 5.2.16 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('story_type', models.CharField(choices=[('learner-story', 'Learner story'), ('case-study', 'Case study'), ('star-learner', 'Star learner')], db_index=True, max_length=24)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('legacy_source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('privacy_approved', models.BooleanField(default=False, help_text='Required before public publication.')),
            ],
            options={
                'ordering': ['sort_order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField()),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
