# Generated by Django 5.2.16 on 2026-08-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('people', '0002_initial'),
        ('programmes', '0002_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='story',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='people.person'),
        ),
        migrations.AddField(
            model_name='story',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='stories.story'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('privacy_approved', True), _connector='OR'), name='published_story_requires_privacy_approval'),
        ),
    ]
