# Generated by Django 5.2.16 on 2026-08-04 12:53

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('microsoft_bookings_url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('lms_url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('aptem_url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('employer_dashboard_url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('privacy_policy_url', models.CharField(blank=True, max_length=300)),
                ('terms_url', models.CharField(blank=True, max_length=300)),
                ('cookie_policy_url', models.CharField(blank=True, max_length=300)),
                ('default_seo_title', models.CharField(blank=True, max_length=70)),
                ('default_seo_description', models.CharField(blank=True, max_length=170)),
                ('alternate_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_site_logos', to='media_library.mediaasset')),
                ('default_open_graph_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_og_defaults', to='media_library.mediaasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logos', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
