# Generated by Django 5.2.16 on 2026-08-04 12:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, validators=[apps.core.validators.validate_https_url])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('legacy_source_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('instructor', 'Instructor'), ('expert', 'Expert'), ('staff', 'Staff'), ('speaker', 'Speaker')], db_index=True, max_length=20)),
            ],
        ),
    ]
