# Generated by Django 5.2.16 on 2026-08-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index,follow', max_length=50)),
                ('open_graph_title', models.CharField(blank=True, max_length=100)),
                ('open_graph_description', models.CharField(blank=True, max_length=200)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=30)),
                ('structured_data', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('open_graph_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediaasset')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_seoreco_content_1bbe8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_seo_record_per_object')],
            },
        ),
    ]
