# Generated by Django 5.2.16 on 2026-08-04 12:52

import apps.newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('consent', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(default=apps.newsletter.models.new_newsletter_reference, editable=False, max_length=32, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
