# Generated by Django 5.2.16 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(max_length=500, unique=True)),
                ('target_path', models.CharField(max_length=1000)),
                ('status_code', models.PositiveSmallIntegerField(default=301)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('preserve_query_string', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['source_path'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status_code__in', [301, 302, 307, 308])), name='valid_redirect_status')],
            },
        ),
    ]
